//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity {

    public My.Namespace.MultipleEntityIndicesComponent myNamespaceMultipleEntityIndices { get { return (My.Namespace.MultipleEntityIndicesComponent)GetComponent(Test2ComponentsLookup.MyNamespaceMultipleEntityIndices); } }
    public bool hasMyNamespaceMultipleEntityIndices { get { return HasComponent(Test2ComponentsLookup.MyNamespaceMultipleEntityIndices); } }

    public Test2Entity AddMyNamespaceMultipleEntityIndices(string newValue, string newValue2) {
        var index = Test2ComponentsLookup.MyNamespaceMultipleEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MultipleEntityIndicesComponent)componentPool.Pop()
            : new My.Namespace.MultipleEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceMyNamespaceMultipleEntityIndices(string newValue, string newValue2) {
        var index = Test2ComponentsLookup.MyNamespaceMultipleEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MultipleEntityIndicesComponent)componentPool.Pop()
            : new My.Namespace.MultipleEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveMyNamespaceMultipleEntityIndices() {
        RemoveComponent(Test2ComponentsLookup.MyNamespaceMultipleEntityIndices);

        return this;
    }


    public Test2Entity SafeRemoveMyNamespaceMultipleEntityIndices() {
        if (hasMyNamespaceMultipleEntityIndices) 
        {
            RemoveComponent(Test2ComponentsLookup.MyNamespaceMultipleEntityIndices);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity : IMyNamespaceMultipleEntityIndicesEntity {
    void IMyNamespaceMultipleEntityIndicesEntity.AddMyNamespaceMultipleEntityIndices(string newValue, string newValue2) { AddMyNamespaceMultipleEntityIndices(newValue, newValue2); }
    void IMyNamespaceMultipleEntityIndicesEntity.ReplaceMyNamespaceMultipleEntityIndices(string newValue, string newValue2) { ReplaceMyNamespaceMultipleEntityIndices(newValue, newValue2); }
    void IMyNamespaceMultipleEntityIndicesEntity.RemoveMyNamespaceMultipleEntityIndices() { RemoveMyNamespaceMultipleEntityIndices(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherMyNamespaceMultipleEntityIndices;

    public static Entitas.IMatcher<Test2Entity> MyNamespaceMultipleEntityIndices {
        get {
            if (_matcherMyNamespaceMultipleEntityIndices == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.MyNamespaceMultipleEntityIndices);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherMyNamespaceMultipleEntityIndices = matcher;
            }

            return _matcherMyNamespaceMultipleEntityIndices;
        }
    }
}
