//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity {

    public Test2ContextComponent test2Context { get { return (Test2ContextComponent)GetComponent(Test2ComponentsLookup.Test2Context); } }
    public bool hasTest2Context { get { return HasComponent(Test2ComponentsLookup.Test2Context); } }

    public Test2Entity AddTest2Context(string newValue) {
        var index = Test2ComponentsLookup.Test2Context;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2ContextComponent)componentPool.Pop()
            : new Test2ContextComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceTest2Context(string newValue) {
        var index = Test2ComponentsLookup.Test2Context;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2ContextComponent)componentPool.Pop()
            : new Test2ContextComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveTest2Context() {
        RemoveComponent(Test2ComponentsLookup.Test2Context);

        return this;
    }


    public Test2Entity SafeRemoveTest2Context() {
        if (hasTest2Context) 
        {
            RemoveComponent(Test2ComponentsLookup.Test2Context);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity : ITest2ContextEntity {
    void ITest2ContextEntity.AddTest2Context(string newValue) { AddTest2Context(newValue); }
    void ITest2ContextEntity.ReplaceTest2Context(string newValue) { ReplaceTest2Context(newValue); }
    void ITest2ContextEntity.RemoveTest2Context() { RemoveTest2Context(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherTest2Context;

    public static Entitas.IMatcher<Test2Entity> Test2Context {
        get {
            if (_matcherTest2Context == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.Test2Context);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherTest2Context = matcher;
            }

            return _matcherTest2Context;
        }
    }
}
