//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity {

    public NameAgeComponent nameAge { get { return (NameAgeComponent)GetComponent(Test2ComponentsLookup.NameAge); } }
    public bool hasNameAge { get { return HasComponent(Test2ComponentsLookup.NameAge); } }

    public Test2Entity AddNameAge(string newName, int newAge) {
        var index = Test2ComponentsLookup.NameAge;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NameAgeComponent)componentPool.Pop()
            : new NameAgeComponent();
        component.name = newName;
        component.age = newAge;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceNameAge(string newName, int newAge) {
        var index = Test2ComponentsLookup.NameAge;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NameAgeComponent)componentPool.Pop()
            : new NameAgeComponent();
        component.name = newName;
        component.age = newAge;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveNameAge() {
        RemoveComponent(Test2ComponentsLookup.NameAge);

        return this;
    }


    public Test2Entity SafeRemoveNameAge() {
        if (hasNameAge) 
        {
            RemoveComponent(Test2ComponentsLookup.NameAge);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity : INameAgeEntity {
    void INameAgeEntity.AddNameAge(string newName, int newAge) { AddNameAge(newName, newAge); }
    void INameAgeEntity.ReplaceNameAge(string newName, int newAge) { ReplaceNameAge(newName, newAge); }
    void INameAgeEntity.RemoveNameAge() { RemoveNameAge(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherNameAge;

    public static Entitas.IMatcher<Test2Entity> NameAge {
        get {
            if (_matcherNameAge == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.NameAge);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherNameAge = matcher;
            }

            return _matcherNameAge;
        }
    }
}
