//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity {

    public My.Namespace.MyNamespaceComponent myNamespaceMyNamespace { get { return (My.Namespace.MyNamespaceComponent)GetComponent(Test2ComponentsLookup.MyNamespaceMyNamespace); } }
    public bool hasMyNamespaceMyNamespace { get { return HasComponent(Test2ComponentsLookup.MyNamespaceMyNamespace); } }

    public Test2Entity AddMyNamespaceMyNamespace(string newValue) {
        var index = Test2ComponentsLookup.MyNamespaceMyNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MyNamespaceComponent)componentPool.Pop()
            : new My.Namespace.MyNamespaceComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceMyNamespaceMyNamespace(string newValue) {
        var index = Test2ComponentsLookup.MyNamespaceMyNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MyNamespaceComponent)componentPool.Pop()
            : new My.Namespace.MyNamespaceComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveMyNamespaceMyNamespace() {
        RemoveComponent(Test2ComponentsLookup.MyNamespaceMyNamespace);

        return this;
    }


    public Test2Entity SafeRemoveMyNamespaceMyNamespace() {
        if (hasMyNamespaceMyNamespace) 
        {
            RemoveComponent(Test2ComponentsLookup.MyNamespaceMyNamespace);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity : IMyNamespaceMyNamespaceEntity {
    void IMyNamespaceMyNamespaceEntity.AddMyNamespaceMyNamespace(string newValue) { AddMyNamespaceMyNamespace(newValue); }
    void IMyNamespaceMyNamespaceEntity.ReplaceMyNamespaceMyNamespace(string newValue) { ReplaceMyNamespaceMyNamespace(newValue); }
    void IMyNamespaceMyNamespaceEntity.RemoveMyNamespaceMyNamespace() { RemoveMyNamespaceMyNamespace(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherMyNamespaceMyNamespace;

    public static Entitas.IMatcher<Test2Entity> MyNamespaceMyNamespace {
        get {
            if (_matcherMyNamespaceMyNamespace == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.MyNamespaceMyNamespace);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherMyNamespaceMyNamespace = matcher;
            }

            return _matcherMyNamespaceMyNamespace;
        }
    }
}
