//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity {

    public ClassToGenerateComponent classToGenerate { get { return (ClassToGenerateComponent)GetComponent(Test2ComponentsLookup.ClassToGenerate); } }
    public bool hasClassToGenerate { get { return HasComponent(Test2ComponentsLookup.ClassToGenerate); } }

    public Test2Entity AddClassToGenerate(My.Namespace.ClassToGenerate newValue) {
        var index = Test2ComponentsLookup.ClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassToGenerateComponent)componentPool.Pop()
            : new ClassToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceClassToGenerate(My.Namespace.ClassToGenerate newValue) {
        var index = Test2ComponentsLookup.ClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassToGenerateComponent)componentPool.Pop()
            : new ClassToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveClassToGenerate() {
        RemoveComponent(Test2ComponentsLookup.ClassToGenerate);

        return this;
    }


    public Test2Entity SafeRemoveClassToGenerate() {
        if (hasClassToGenerate) 
        {
            RemoveComponent(Test2ComponentsLookup.ClassToGenerate);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class Test2Entity : IClassToGenerateEntity {
    void IClassToGenerateEntity.AddClassToGenerate(My.Namespace.ClassToGenerate newValue) { AddClassToGenerate(newValue); }
    void IClassToGenerateEntity.ReplaceClassToGenerate(My.Namespace.ClassToGenerate newValue) { ReplaceClassToGenerate(newValue); }
    void IClassToGenerateEntity.RemoveClassToGenerate() { RemoveClassToGenerate(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherClassToGenerate;

    public static Entitas.IMatcher<Test2Entity> ClassToGenerate {
        get {
            if (_matcherClassToGenerate == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.ClassToGenerate);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherClassToGenerate = matcher;
            }

            return _matcherClassToGenerate;
        }
    }
}
