//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public PrimaryEntityIndexComponent primaryEntityIndex { get { return (PrimaryEntityIndexComponent)GetComponent(GameComponentsLookup.PrimaryEntityIndex); } }
    public bool hasPrimaryEntityIndex { get { return HasComponent(GameComponentsLookup.PrimaryEntityIndex); } }

    public GameEntity AddPrimaryEntityIndex(string newValue) {
        var index = GameComponentsLookup.PrimaryEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (PrimaryEntityIndexComponent)componentPool.Pop()
            : new PrimaryEntityIndexComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public GameEntity ReplacePrimaryEntityIndex(string newValue) {
        var index = GameComponentsLookup.PrimaryEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (PrimaryEntityIndexComponent)componentPool.Pop()
            : new PrimaryEntityIndexComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public GameEntity RemovePrimaryEntityIndex() {
        RemoveComponent(GameComponentsLookup.PrimaryEntityIndex);

        return this;
    }


    public GameEntity SafeRemovePrimaryEntityIndex() {
        if (hasPrimaryEntityIndex) 
        {
            RemoveComponent(GameComponentsLookup.PrimaryEntityIndex);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherPrimaryEntityIndex;

    public static Entitas.IMatcher<GameEntity> PrimaryEntityIndex {
        get {
            if (_matcherPrimaryEntityIndex == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.PrimaryEntityIndex);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherPrimaryEntityIndex = matcher;
            }

            return _matcherPrimaryEntityIndex;
        }
    }
}
