//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public ParentComponent parent { get { return (ParentComponent)GetComponent(GameComponentsLookup.Parent); } }
    public bool hasParent { get { return HasComponent(GameComponentsLookup.Parent); } }

    public GameEntity AddParent(float newValue) {
        var index = GameComponentsLookup.Parent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ParentComponent)componentPool.Pop()
            : new ParentComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public GameEntity ReplaceParent(float newValue) {
        var index = GameComponentsLookup.Parent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ParentComponent)componentPool.Pop()
            : new ParentComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public GameEntity RemoveParent() {
        RemoveComponent(GameComponentsLookup.Parent);

        return this;
    }


    public GameEntity SafeRemoveParent() {
        if (hasParent) 
        {
            RemoveComponent(GameComponentsLookup.Parent);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherParent;

    public static Entitas.IMatcher<GameEntity> Parent {
        get {
            if (_matcherParent == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Parent);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherParent = matcher;
            }

            return _matcherParent;
        }
    }
}
