//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class GameEntity {

    public MultiplePrimaryEntityIndicesComponent multiplePrimaryEntityIndices { get { return (MultiplePrimaryEntityIndicesComponent)GetComponent(GameComponentsLookup.MultiplePrimaryEntityIndices); } }
    public bool hasMultiplePrimaryEntityIndices { get { return HasComponent(GameComponentsLookup.MultiplePrimaryEntityIndices); } }

    public GameEntity AddMultiplePrimaryEntityIndices(string newValue, string newValue2) {
        var index = GameComponentsLookup.MultiplePrimaryEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultiplePrimaryEntityIndicesComponent)componentPool.Pop()
            : new MultiplePrimaryEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        AddComponent(index, component);

        return this;
    }

    public GameEntity ReplaceMultiplePrimaryEntityIndices(string newValue, string newValue2) {
        var index = GameComponentsLookup.MultiplePrimaryEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultiplePrimaryEntityIndicesComponent)componentPool.Pop()
            : new MultiplePrimaryEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        ReplaceComponent(index, component);

        return this;
    }

    public GameEntity RemoveMultiplePrimaryEntityIndices() {
        RemoveComponent(GameComponentsLookup.MultiplePrimaryEntityIndices);

        return this;
    }


    public GameEntity SafeRemoveMultiplePrimaryEntityIndices() {
        if (hasMultiplePrimaryEntityIndices) 
        {
            RemoveComponent(GameComponentsLookup.MultiplePrimaryEntityIndices);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherMultiplePrimaryEntityIndices;

    public static Entitas.IMatcher<GameEntity> MultiplePrimaryEntityIndices {
        get {
            if (_matcherMultiplePrimaryEntityIndices == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.MultiplePrimaryEntityIndices);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherMultiplePrimaryEntityIndices = matcher;
            }

            return _matcherMultiplePrimaryEntityIndices;
        }
    }
}
