using System.Collections.Generic;
using System.Linq;
using System.Text;
using Entitas.SourceGenerator.CodeGeneration;
using Entitas.SourceGenerator.Discovery;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Entitas.SourceGenerator
{
    /// <summary>
    /// The real Entitas-Flux Roslyn incremental source generator. It runs every
    /// ported code generator over the discovered data model and emits each
    /// resulting fragment as its own compilation unit.
    ///
    /// Pipeline note: we feed the whole <see cref="Compilation"/> via
    /// <c>CompilationProvider</c> for correctness now (discovery needs the full
    /// semantic model plus the assembly-level [ContextDefinition] list). Finer-
    /// grained incremental caching (syntax-predicate driven) is a later optimization.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EntitasIncrementalGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pipeline = context.CompilationProvider;
            context.RegisterSourceOutput(pipeline, Execute);
        }

        static void Execute(SourceProductionContext spc, Compilation compilation)
        {
            // EntitasGenerators.Generate is the single source of truth (opt-in guard,
            // config, discovery, generation and FileName merge) shared with the CLI; here
            // we just AddSource each merged file with a unique hint name.
            var hintNames = new HashSet<string>();
            foreach (var source in EntitasGenerators.Generate(compilation))
            {
                var sb = new StringBuilder();
                sb.Append("// <auto-generated/>\n");
                sb.Append(source.Content);
                spc.AddSource(BuildHintName(source.FileName, hintNames), SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        /// <summary>
        /// Derives a globally-unique Roslyn hint name from a logical FileName (the same
        /// path the legacy Jenny pipeline used). All fragments sharing a FileName are
        /// merged into one source, so the FileName alone is the key; a trailing counter
        /// guards against any residual collision.
        ///
        /// Public so power-users running their own <see cref="AbstractGenerator"/>s from
        /// their own analyzer can group their <see cref="CodeGenFile"/>s by FileName and
        /// derive hint names the same way the framework does. Pass a per-run
        /// <see cref="HashSet{T}"/> to dedupe across calls.
        /// </summary>
        public static string BuildHintName(string fileName, HashSet<string> taken)
        {
            var baseName = Sanitize(fileName);
            var candidate = baseName + ".g.cs";

            var counter = 1;
            while (!taken.Add(candidate))
                candidate = $"{baseName}_{counter++}.g.cs";

            return candidate;
        }

        static string Sanitize(string value)
        {
            if (string.IsNullOrEmpty(value))
                return "_";

            var sb = new StringBuilder(value.Length);
            foreach (var c in value)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');

            var s = sb.ToString();
            if (s.EndsWith("_cs"))
                s = s.Substring(0, s.Length - "_cs".Length);
            return s;
        }
    }
}
