using System.Collections.Generic;
using System.Linq;
using System.Text;
using Entitas.SourceGenerator.CodeGeneration;
using Entitas.SourceGenerator.Discovery;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Entitas.SourceGenerator
{
    /// <summary>
    /// The real Entitas-Flux Roslyn incremental source generator. It runs every
    /// ported code generator over the discovered data model and emits each
    /// resulting fragment as its own compilation unit.
    ///
    /// Pipeline: the compilation is projected into a <see cref="GenerationInput"/> — a
    /// value built from per-type <see cref="TypeSnapshot"/>s, holding no symbols and no
    /// syntax — and generation hangs off THAT. Roslyn re-runs the projection on every
    /// keystroke (deciding what is a component is semantic), but compares its result by
    /// value, so an edit that changes no component, attribute or config leaves the input
    /// equal and the entire generation half of the pipeline is skipped.
    ///
    /// This is why snapshots and the input model must stay equatable and free of
    /// anything rooted in a compilation. Put a symbol in there and the caching silently
    /// stops working (see IncrementalityTests).
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class EntitasIncrementalGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // NOTE: a SyntaxProvider pipeline (snapshot each type declaration, collect,
            // combine with the config) was built and measured against this one on a real
            // 2247-file project. It was 3.8x SLOWER per keystroke (146 ms vs 38 ms) and
            // 2.2x slower cold. The reason is structural, not a tuning problem: deciding
            // whether a type is a component is a SEMANTIC question, and Roslyn re-runs
            // every semantic transform when the compilation changes — a single-file edit
            // re-ran the snapshot transform 2968 times — so the syntax pipeline redoes
            // all of the work anyway and adds per-node bookkeeping on top.
            // ForAttributeWithMetadataName would avoid that, but only for attribute-
            // marked types, and a component here is defined by implementing IComponent.
            // Narrowing the predicate changed nothing (145 ms). Don't re-try this without
            // new measurements.
            var pipeline = context.CompilationProvider.Select(static (compilation, _) => GenerationInput.From(compilation));

            context.RegisterSourceOutput(pipeline, Execute);
        }

        static void Execute(SourceProductionContext spc, GenerationInput input)
        {
            // EntitasGenerators.Generate is the single source of truth (config,
            // generation and FileName merge) shared with the CLIs; here we report its
            // diagnostics and AddSource each merged file with a unique hint name.
            var result = EntitasGenerators.Generate(input);

            foreach (var diagnostic in result.Diagnostics)
                spc.ReportDiagnostic(diagnostic);

            var hintNames = new HashSet<string>();
            foreach (var source in result.Sources)
            {
                var sb = new StringBuilder();
                sb.Append("// <auto-generated/>\n");
                sb.Append(source.Content);
                spc.AddSource(BuildHintName(source.FileName, hintNames), SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }

        /// <summary>
        /// Derives a globally-unique Roslyn hint name from a logical FileName (the same
        /// path the legacy Jenny pipeline used). All fragments sharing a FileName are
        /// merged into one source, so the FileName alone is the key; a trailing counter
        /// guards against any residual collision.
        ///
        /// Public so power-users running their own <see cref="AbstractGenerator"/>s from
        /// their own analyzer can group their <see cref="CodeGenFile"/>s by FileName and
        /// derive hint names the same way the framework does. Pass a per-run
        /// <see cref="HashSet{T}"/> to dedupe across calls.
        /// </summary>
        public static string BuildHintName(string fileName, HashSet<string> taken)
        {
            var baseName = Sanitize(fileName);
            var candidate = baseName + ".g.cs";

            var counter = 1;
            while (!taken.Add(candidate))
                candidate = $"{baseName}_{counter++}.g.cs";

            return candidate;
        }

        static string Sanitize(string value)
        {
            if (string.IsNullOrEmpty(value))
                return "_";

            var sb = new StringBuilder(value.Length);
            foreach (var c in value)
                sb.Append(char.IsLetterOrDigit(c) ? c : '_');

            var s = sb.ToString();
            if (s.EndsWith("_cs"))
                s = s.Substring(0, s.Length - "_cs".Length);
            return s;
        }
    }
}
