using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Xml.Linq;
using Entitas.SourceGenerator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Entitas.SourceGenerator.Cli
{
    /// <summary>
    /// Standalone, Jenny-style code generator. Parses a Unity-generated
    /// Assembly-CSharp.csproj into a Roslyn <see cref="Compilation"/> and runs the
    /// Entitas-Flux source-generator engine, writing the merged output to disk as real
    /// .cs files (an alternative to the compile-time analyzer for consumers that want
    /// committed / debuggable generated code).
    /// </summary>
    internal static class Program
    {
        const string Header =
            "//------------------------------------------------------------------------------\n" +
            "// <auto-generated>\n" +
            "//     This code was generated by the Entitas source generator.\n" +
            "//\n" +
            "//     Changes to this file may cause incorrect behavior and will be lost if\n" +
            "//     the code is regenerated.\n" +
            "// </auto-generated>\n" +
            "//------------------------------------------------------------------------------\n" +
            "\n";

        static int Main(string[] args)
        {
            if (args.Length != 2)
            {
                Console.Error.WriteLine("Usage: entitas-gen <Assembly-CSharp.csproj> <output-dir>");
                Console.Error.WriteLine();
                Console.Error.WriteLine("  <Assembly-CSharp.csproj>  Path to a Unity-generated C# project file.");
                Console.Error.WriteLine("  <output-dir>              Dedicated folder for generated .cs files.");
                Console.Error.WriteLine("                            WARNING: its contents are deleted before writing.");
                return 2;
            }

            var csprojPath = Path.GetFullPath(args[0]);
            var outputDir = Path.GetFullPath(args[1]);

            try
            {
                if (!File.Exists(csprojPath))
                {
                    Console.Error.WriteLine($"error: csproj not found: {csprojPath}");
                    return 1;
                }

                var project = ParseProject(csprojPath);

                if (project.SourceFiles.Count == 0)
                {
                    Console.Error.WriteLine($"error: no <Compile> source files found in {csprojPath}");
                    return 1;
                }

                var compilation = BuildCompilation(csprojPath, project);

                var sources = EntitasGenerators.Generate(compilation);
                if (sources.Count == 0)
                {
                    Console.Error.WriteLine(
                        "error: the engine produced no output. The assembly must reference Entitas " +
                        "(Entitas.IComponent) AND declare at least one [assembly: ContextDefinition(\"...\")]. " +
                        "Check that the csproj's <Compile> items include the file with those attributes and " +
                        "that the Entitas reference resolves.");
                    return 1;
                }

                WriteOutput(outputDir, sources);

                Console.WriteLine($"Generated {sources.Count} files in {outputDir}");
                return 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"error: {ex.Message}");
                return 1;
            }
        }

        /// <summary>
        /// Parses a legacy, non-SDK Unity csproj (MSBuild XML namespace
        /// http://schemas.microsoft.com/developer/msbuild/2003). All element lookups are
        /// namespace-agnostic (compare <see cref="XName.LocalName"/>), and relative paths
        /// are resolved against the csproj's directory with backslashes normalized.
        /// </summary>
        static ProjectInfo ParseProject(string csprojPath)
        {
            var projectDir = Path.GetDirectoryName(csprojPath)!;
            var doc = XDocument.Load(csprojPath);
            var root = doc.Root ?? throw new InvalidOperationException("csproj has no root element.");

            var sourceFiles = new List<string>();
            var references = new List<string>();
            var defines = new List<string>();

            foreach (var element in root.Descendants())
            {
                switch (element.Name.LocalName)
                {
                    case "Compile":
                    {
                        var include = element.Attribute("Include")?.Value;
                        var resolved = ResolvePath(projectDir, include);
                        if (resolved != null && File.Exists(resolved))
                            sourceFiles.Add(resolved);
                        break;
                    }
                    case "Reference":
                    {
                        var hintPath = element.Elements()
                            .FirstOrDefault(e => e.Name.LocalName == "HintPath")?.Value;
                        var resolved = ResolvePath(projectDir, hintPath);
                        if (resolved != null && File.Exists(resolved))
                            references.Add(resolved);
                        break;
                    }
                    case "DefineConstants":
                    {
                        foreach (var symbol in element.Value.Split(';'))
                        {
                            var trimmed = symbol.Trim();
                            if (trimmed.Length > 0)
                                defines.Add(trimmed);
                        }
                        break;
                    }
                }
            }

            return new ProjectInfo(
                sourceFiles,
                references,
                defines.Distinct(StringComparer.Ordinal).ToList());
        }

        static string? ResolvePath(string projectDir, string? raw)
        {
            if (string.IsNullOrWhiteSpace(raw))
                return null;

            var normalized = raw.Replace('\\', Path.DirectorySeparatorChar)
                                .Replace('/', Path.DirectorySeparatorChar)
                                .Trim();

            return Path.IsPathRooted(normalized)
                ? Path.GetFullPath(normalized)
                : Path.GetFullPath(Path.Combine(projectDir, normalized));
        }

        static CSharpCompilation BuildCompilation(string csprojPath, ProjectInfo project)
        {
            var parseOptions = new CSharpParseOptions(preprocessorSymbols: project.Defines);

            var trees = project.SourceFiles
                .Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f), parseOptions, path: f))
                .ToArray();

            var references = project.References
                .Select(r => (MetadataReference)MetadataReference.CreateFromFile(r))
                .ToList();

            // Fall back to the running runtime's BCL only if the csproj resolved no
            // references at all (Unity's csproj references mscorlib/netstandard, so this
            // is just a safety net for malformed inputs).
            if (references.Count == 0)
                references.AddRange(GetRuntimeReferences());

            var assemblyName = Path.GetFileNameWithoutExtension(csprojPath);
            var options = new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                allowUnsafe: true);

            return CSharpCompilation.Create(assemblyName, trees, references, options);
        }

        static IEnumerable<MetadataReference> GetRuntimeReferences()
        {
            var tpa = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
            if (string.IsNullOrEmpty(tpa))
                return Array.Empty<MetadataReference>();

            return tpa.Split(Path.PathSeparator)
                .Where(p => p.Length > 0 && File.Exists(p))
                .Select(p => (MetadataReference)MetadataReference.CreateFromFile(p))
                .ToList();
        }

        /// <summary>
        /// Recreates the (dedicated) output directory and writes each generated source as
        /// a real .cs file with a Jenny-style auto-generated header. The output dir is
        /// cleared first so stale files from previous runs are removed; it must therefore
        /// be a dedicated generated folder.
        /// </summary>
        static void WriteOutput(string outputDir, IReadOnlyList<GeneratedSource> sources)
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
            Directory.CreateDirectory(outputDir);

            foreach (var source in sources)
            {
                var relative = source.FileName
                    .Replace('/', Path.DirectorySeparatorChar)
                    .Replace('\\', Path.DirectorySeparatorChar);

                var fullPath = Path.Combine(outputDir, relative);
                var parent = Path.GetDirectoryName(fullPath);
                if (!string.IsNullOrEmpty(parent))
                    Directory.CreateDirectory(parent);

                File.WriteAllText(fullPath, Header + source.Content);
            }
        }

        sealed class ProjectInfo
        {
            public IReadOnlyList<string> SourceFiles { get; }
            public IReadOnlyList<string> References { get; }
            public IReadOnlyList<string> Defines { get; }

            public ProjectInfo(
                IReadOnlyList<string> sourceFiles,
                IReadOnlyList<string> references,
                IReadOnlyList<string> defines)
            {
                SourceFiles = sourceFiles;
                References = references;
                Defines = defines;
            }
        }
    }
}
