using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Entitas.SourceGenerator;
using Microsoft.CodeAnalysis;

namespace Entitas.SourceGenerator.Cli
{
    /// <summary>
    /// Standalone, Jenny-style code generator. Parses a Unity-generated
    /// Assembly-CSharp.csproj into a Roslyn <see cref="Compilation"/> and runs the
    /// Entitas-Flux source-generator engine, writing the merged output to disk as real
    /// .cs files (an alternative to the compile-time analyzer for consumers that want
    /// committed / debuggable generated code).
    /// </summary>
    internal static class Program
    {
        const string Header =
            "//------------------------------------------------------------------------------\n" +
            "// <auto-generated>\n" +
            "//     This code was generated by the Entitas source generator.\n" +
            "//\n" +
            "//     Changes to this file may cause incorrect behavior and will be lost if\n" +
            "//     the code is regenerated.\n" +
            "// </auto-generated>\n" +
            "//------------------------------------------------------------------------------\n" +
            "\n";

        static int Main(string[] args)
        {
            if (args.Length != 2)
            {
                Console.Error.WriteLine("Usage: entitas-gen <Assembly-CSharp.csproj> <output-dir>");
                Console.Error.WriteLine();
                Console.Error.WriteLine("  <Assembly-CSharp.csproj>  Path to a Unity-generated C# project file.");
                Console.Error.WriteLine("  <output-dir>              Dedicated folder for generated .cs files.");
                Console.Error.WriteLine("                            WARNING: its contents are deleted before writing.");
                return 2;
            }

            var csprojPath = Path.GetFullPath(args[0]);
            var outputDir = Path.GetFullPath(args[1]);

            try
            {
                if (!File.Exists(csprojPath))
                {
                    Console.Error.WriteLine($"error: csproj not found: {csprojPath}");
                    return 1;
                }

                var project = ProjectLoader.ParseProject(csprojPath);

                if (project.SourceFiles.Count == 0)
                {
                    Console.Error.WriteLine($"error: no <Compile> source files found in {csprojPath}");
                    return 1;
                }

                var compilation = ProjectLoader.BuildCompilation(csprojPath, project);

                var result = EntitasGenerators.Generate(GenerationInput.From(compilation));
                foreach (var diagnostic in result.Diagnostics)
                    Console.Error.WriteLine(diagnostic.ToString());

                var sources = result.Sources;
                if (sources.Count == 0)
                {
                    Console.Error.WriteLine(
                        "error: the engine produced no output. The assembly must reference Entitas " +
                        "(Entitas.IComponent) AND declare at least one [assembly: ContextDefinition(\"...\")]. " +
                        "Check that the csproj's <Compile> items include the file with those attributes and " +
                        "that the Entitas reference resolves.");
                    return 1;
                }

                WriteOutput(outputDir, sources);

                Console.WriteLine($"Generated {sources.Count} files in {outputDir}");

                // A generator that failed leaves a hole in the generated API; the caller
                // (a build, usually) must not treat that as success.
                return result.Diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error) ? 1 : 0;
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"error: {ex.Message}");
                return 1;
            }
        }

        /// <summary>
        /// Recreates the (dedicated) output directory and writes each generated source as
        /// a real .cs file with a Jenny-style auto-generated header. The output dir is
        /// cleared first so stale files from previous runs are removed; it must therefore
        /// be a dedicated generated folder.
        /// </summary>
        static void WriteOutput(string outputDir, IReadOnlyList<GeneratedSource> sources)
        {
            if (Directory.Exists(outputDir))
                Directory.Delete(outputDir, recursive: true);
            Directory.CreateDirectory(outputDir);

            foreach (var source in sources)
            {
                var relative = source.FileName
                    .Replace('/', Path.DirectorySeparatorChar)
                    .Replace('\\', Path.DirectorySeparatorChar);

                var fullPath = Path.Combine(outputDir, relative);
                var parent = Path.GetDirectoryName(fullPath);
                if (!string.IsNullOrEmpty(parent))
                    Directory.CreateDirectory(parent);

                File.WriteAllText(fullPath, Header + source.Content);
            }
        }

    }
}
