// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class InterfaceToGenerateComponent : Entitas.IComponent {
    public My.Namespace.InterfaceToGenerate value;
}

