// <auto-generated/>
public partial interface INameAgeEntity {

    NameAgeComponent nameAge { get; }
    bool hasNameAge { get; }

    void AddNameAge(string newName, int newAge);
    void ReplaceNameAge(string newName, int newAge);
    void RemoveNameAge();
}

