// <auto-generated/>
public partial interface IMyNamespaceEntityIndexEntity {

    My.Namespace.EntityIndexComponent myNamespaceEntityIndex { get; }
    bool hasMyNamespaceEntityIndex { get; }

    void AddMyNamespaceEntityIndex(string newValue);
    void ReplaceMyNamespaceEntityIndex(string newValue);
    void RemoveMyNamespaceEntityIndex();
}

