// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class UniqueClassToGenerateComponent : Entitas.IComponent {
    public My.Namespace.UniqueClassToGenerate value;
}

