// <auto-generated/>
public partial interface IClassToGenerateEntity {

    ClassToGenerateComponent classToGenerate { get; }
    bool hasClassToGenerate { get; }

    void AddClassToGenerate(My.Namespace.ClassToGenerate newValue);
    void ReplaceClassToGenerate(My.Namespace.ClassToGenerate newValue);
    void RemoveClassToGenerate();
}

