// <auto-generated/>
public partial interface IMyNamespaceMyNamespaceEntity {

    My.Namespace.MyNamespaceComponent myNamespaceMyNamespace { get; }
    bool hasMyNamespaceMyNamespace { get; }

    void AddMyNamespaceMyNamespace(string newValue);
    void ReplaceMyNamespaceMyNamespace(string newValue);
    void RemoveMyNamespaceMyNamespace();
}

