// <auto-generated/>
public partial interface IEventToGenerateEntity {

    EventToGenerateComponent eventToGenerate { get; }
    bool hasEventToGenerate { get; }

    void AddEventToGenerate(My.Namespace.EventToGenerate newValue);
    void ReplaceEventToGenerate(My.Namespace.EventToGenerate newValue);
    void RemoveEventToGenerate();
}

