// <auto-generated/>
public partial interface IMyNamespaceMultipleEntityIndicesEntity {

    My.Namespace.MultipleEntityIndicesComponent myNamespaceMultipleEntityIndices { get; }
    bool hasMyNamespaceMultipleEntityIndices { get; }

    void AddMyNamespaceMultipleEntityIndices(string newValue, string newValue2);
    void ReplaceMyNamespaceMultipleEntityIndices(string newValue, string newValue2);
    void RemoveMyNamespaceMultipleEntityIndices();
}

