// <auto-generated/>
public partial interface IMultipleEventsStandardEventEntity {

    MultipleEventsStandardEventComponent multipleEventsStandardEvent { get; }
    bool hasMultipleEventsStandardEvent { get; }

    void AddMultipleEventsStandardEvent(string newValue);
    void ReplaceMultipleEventsStandardEvent(string newValue);
    void RemoveMultipleEventsStandardEvent();
}

