// <auto-generated/>
public partial interface ITest2ContextEntity {

    Test2ContextComponent test2Context { get; }
    bool hasTest2Context { get; }

    void AddTest2Context(string newValue);
    void ReplaceTest2Context(string newValue);
    void RemoveTest2Context();
}

