// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class ClassWithEntitIndexAttributeComponent : Entitas.IComponent {
    public ClassWithEntitIndexAttribute value;
}

