// <auto-generated/>
public partial interface IMultipleContextStandardEventEntity {

    MultipleContextStandardEventComponent multipleContextStandardEvent { get; }
    bool hasMultipleContextStandardEvent { get; }

    void AddMultipleContextStandardEvent(string newValue);
    void ReplaceMultipleContextStandardEvent(string newValue);
    void RemoveMultipleContextStandardEvent();
}

