// <auto-generated/>
public partial interface IUniqueClassToGenerateEntity {

    UniqueClassToGenerateComponent uniqueClassToGenerate { get; }
    bool hasUniqueClassToGenerate { get; }

    void AddUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue);
    void ReplaceUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue);
    void RemoveUniqueClassToGenerate();
}

