// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class Test2AnyMultipleContextStandardEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITest2AnyMultipleContextStandardEventListener> value;
}

