// <auto-generated/>
public sealed class Test2EventSystems : Feature {

    public Test2EventSystems(Contexts contexts) {
        Add(new Test2AnyEventToGenerateEventSystem(contexts)); // priority: 0
        Add(new Test2AnyMultipleContextStandardEventEventSystem(contexts)); // priority: 0
        Add(new Test2AnyMultipleEventsStandardEventEventSystem(contexts)); // priority: 1
        Add(new Test2MultipleEventsStandardEventRemovedEventSystem(contexts)); // priority: 2
    }
}

