// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class TestAnyEventToGenerateListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITestAnyEventToGenerateListener> value;
}

