// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class AnyStandardEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IAnyStandardEventListener> value;
}

