// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class FlagEntityEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IFlagEntityEventListener> value;
}

