// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class TestAnyMultipleContextStandardEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITestAnyMultipleContextStandardEventListener> value;
}

