// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class Test2MultipleEventsStandardEventRemovedListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITest2MultipleEventsStandardEventRemovedListener> value;
}

