// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class TestMultipleEventsStandardEventRemovedListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITestMultipleEventsStandardEventRemovedListener> value;
}

