// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class MixedEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IMixedEventListener> value;
}

