// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class Test2AnyEventToGenerateListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITest2AnyEventToGenerateListener> value;
}

