// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class AnyFlagEventRemovedListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IAnyFlagEventRemovedListener> value;
}

