// <auto-generated/>
public sealed class TestEventSystems : Feature {

    public TestEventSystems(Contexts contexts) {
        Add(new TestAnyEventToGenerateEventSystem(contexts)); // priority: 0
        Add(new AnyFlagEventRemovedEventSystem(contexts)); // priority: 0
        Add(new AnyMixedEventEventSystem(contexts)); // priority: 0
        Add(new MixedEventEventSystem(contexts)); // priority: 0
        Add(new TestAnyMultipleContextStandardEventEventSystem(contexts)); // priority: 0
        Add(new AnyStandardEventEventSystem(contexts)); // priority: 0
        Add(new AnyUniqueEventEventSystem(contexts)); // priority: 0
        Add(new FlagEntityEventEventSystem(contexts)); // priority: 1
        Add(new TestAnyMultipleEventsStandardEventEventSystem(contexts)); // priority: 1
        Add(new StandardEntityEventRemovedEventSystem(contexts)); // priority: 1
        Add(new TestMultipleEventsStandardEventRemovedEventSystem(contexts)); // priority: 2
    }
}

