// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class AnyUniqueEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IAnyUniqueEventListener> value;
}

