// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class TestAnyMultipleEventsStandardEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<ITestAnyMultipleEventsStandardEventListener> value;
}

