// <auto-generated/>
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class AnyMixedEventListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<IAnyMixedEventListener> value;
}

