// <auto-generated/>
public partial class GameEntity {

    static readonly MyNamespaceWatchedInNamespaceChanged myNamespaceWatchedInNamespaceChangedComponent = new MyNamespaceWatchedInNamespaceChanged();

    public bool isMyNamespaceWatchedInNamespaceChanged {
        get { return HasComponent(GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged); }
        set {
            if (value != isMyNamespaceWatchedInNamespaceChanged) {
                var index = GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : myNamespaceWatchedInNamespaceChangedComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherMyNamespaceWatchedInNamespaceChanged;

    public static Entitas.IMatcher<GameEntity> MyNamespaceWatchedInNamespaceChanged {
        get {
            if (_matcherMyNamespaceWatchedInNamespaceChanged == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherMyNamespaceWatchedInNamespaceChanged = matcher;
            }

            return _matcherMyNamespaceWatchedInNamespaceChanged;
        }
    }
}

