// <auto-generated/>
public partial class GameEntity {

    public MyNamespace.WatchedInNamespaceComponent myNamespaceWatchedInNamespace { get { return (MyNamespace.WatchedInNamespaceComponent)GetComponent(GameComponentsLookup.MyNamespaceWatchedInNamespace); } }
    public bool hasMyNamespaceWatchedInNamespace { get { return HasComponent(GameComponentsLookup.MyNamespaceWatchedInNamespace); } }

    public GameEntity AddMyNamespaceWatchedInNamespace(int newValue) {
        var index = GameComponentsLookup.MyNamespaceWatchedInNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyNamespace.WatchedInNamespaceComponent)componentPool.Pop()
            : new MyNamespace.WatchedInNamespaceComponent();
        component.value = newValue;
        AddComponent(index, component);
        isMyNamespaceWatchedInNamespaceChanged = true;

        return this;
    }

    public GameEntity ReplaceMyNamespaceWatchedInNamespace(int newValue) {
        var index = GameComponentsLookup.MyNamespaceWatchedInNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MyNamespace.WatchedInNamespaceComponent)componentPool.Pop()
            : new MyNamespace.WatchedInNamespaceComponent();
        component.value = newValue;
        ReplaceComponent(index, component);
        isMyNamespaceWatchedInNamespaceChanged = true;

        return this;
    }

    public GameEntity RemoveMyNamespaceWatchedInNamespace() {
        RemoveComponent(GameComponentsLookup.MyNamespaceWatchedInNamespace);
        isMyNamespaceWatchedInNamespaceChanged = true;

        return this;
    }


    public GameEntity SafeRemoveMyNamespaceWatchedInNamespace() {
        if (hasMyNamespaceWatchedInNamespace)
        {
            RemoveComponent(GameComponentsLookup.MyNamespaceWatchedInNamespace);
            isMyNamespaceWatchedInNamespaceChanged = true;
        }

        return this;
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherMyNamespaceWatchedInNamespace;

    public static Entitas.IMatcher<GameEntity> MyNamespaceWatchedInNamespace {
        get {
            if (_matcherMyNamespaceWatchedInNamespace == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.MyNamespaceWatchedInNamespace);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherMyNamespaceWatchedInNamespace = matcher;
            }

            return _matcherMyNamespaceWatchedInNamespace;
        }
    }
}

