// <auto-generated/>
public partial class GameEntity {

    public WatchedValueComponent watchedValue { get { return (WatchedValueComponent)GetComponent(GameComponentsLookup.WatchedValue); } }
    public bool hasWatchedValue { get { return HasComponent(GameComponentsLookup.WatchedValue); } }

    public GameEntity AddWatchedValue(int newValue) {
        var index = GameComponentsLookup.WatchedValue;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (WatchedValueComponent)componentPool.Pop()
            : new WatchedValueComponent();
        component.value = newValue;
        AddComponent(index, component);
        isWatchedValueChanged = true;

        return this;
    }

    public GameEntity ReplaceWatchedValue(int newValue) {
        var index = GameComponentsLookup.WatchedValue;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (WatchedValueComponent)componentPool.Pop()
            : new WatchedValueComponent();
        component.value = newValue;
        ReplaceComponent(index, component);
        isWatchedValueChanged = true;

        return this;
    }

    public GameEntity RemoveWatchedValue() {
        RemoveComponent(GameComponentsLookup.WatchedValue);
        isWatchedValueChanged = true;

        return this;
    }


    public GameEntity SafeRemoveWatchedValue() {
        if (hasWatchedValue)
        {
            RemoveComponent(GameComponentsLookup.WatchedValue);
            isWatchedValueChanged = true;
        }

        return this;
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherWatchedValue;

    public static Entitas.IMatcher<GameEntity> WatchedValue {
        get {
            if (_matcherWatchedValue == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.WatchedValue);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherWatchedValue = matcher;
            }

            return _matcherWatchedValue;
        }
    }
}

