// <auto-generated/>
using System.Collections.Generic;
using Entitas;

public sealed class RemoveWatchedFlagChangedGameSystem : ICleanupSystem {

    readonly IGroup<GameEntity> _group;
    readonly List<GameEntity> _buffer = new List<GameEntity>(8);

    public RemoveWatchedFlagChangedGameSystem(Contexts contexts) {
        _group = contexts.game.GetGroup(GameMatcher.WatchedFlagChanged);
    }

    public void Cleanup() {
        foreach (var e in _group.GetEntities(_buffer)) {
            e.isWatchedFlagChanged = false;
        }
    }
}

