// <auto-generated/>
public partial class GameEntity {

    static readonly WatchedFlagChanged watchedFlagChangedComponent = new WatchedFlagChanged();

    public bool isWatchedFlagChanged {
        get { return HasComponent(GameComponentsLookup.WatchedFlagChanged); }
        set {
            if (value != isWatchedFlagChanged) {
                var index = GameComponentsLookup.WatchedFlagChanged;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : watchedFlagChangedComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherWatchedFlagChanged;

    public static Entitas.IMatcher<GameEntity> WatchedFlagChanged {
        get {
            if (_matcherWatchedFlagChanged == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.WatchedFlagChanged);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherWatchedFlagChanged = matcher;
            }

            return _matcherWatchedFlagChanged;
        }
    }
}

