// <auto-generated/>
public partial class GameEntity {

    static readonly WatchedValueChanged watchedValueChangedComponent = new WatchedValueChanged();

    public bool isWatchedValueChanged {
        get { return HasComponent(GameComponentsLookup.WatchedValueChanged); }
        set {
            if (value != isWatchedValueChanged) {
                var index = GameComponentsLookup.WatchedValueChanged;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : watchedValueChangedComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherWatchedValueChanged;

    public static Entitas.IMatcher<GameEntity> WatchedValueChanged {
        get {
            if (_matcherWatchedValueChanged == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.WatchedValueChanged);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherWatchedValueChanged = matcher;
            }

            return _matcherWatchedValueChanged;
        }
    }
}

