// <auto-generated/>
public partial class GameEntity {

    public InheritedComponent inherited { get { return (InheritedComponent)GetComponent(GameComponentsLookup.Inherited); } }
    public bool hasInherited { get { return HasComponent(GameComponentsLookup.Inherited); } }

    public GameEntity AddInherited(float newValue) {
        var index = GameComponentsLookup.Inherited;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (InheritedComponent)componentPool.Pop()
            : new InheritedComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public GameEntity ReplaceInherited(float newValue) {
        var index = GameComponentsLookup.Inherited;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (InheritedComponent)componentPool.Pop()
            : new InheritedComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public GameEntity RemoveInherited() {
        RemoveComponent(GameComponentsLookup.Inherited);

        return this;
    }


    public GameEntity SafeRemoveInherited() {
        if (hasInherited)
        {
            RemoveComponent(GameComponentsLookup.Inherited);
        }

        return this;
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherInherited;

    public static Entitas.IMatcher<GameEntity> Inherited {
        get {
            if (_matcherInherited == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Inherited);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherInherited = matcher;
            }

            return _matcherInherited;
        }
    }
}

