// <auto-generated/>
using System.Collections.Generic;
using Entitas;

public sealed class RemoveMyNamespaceWatchedInNamespaceChangedGameSystem : ICleanupSystem {

    readonly IGroup<GameEntity> _group;
    readonly List<GameEntity> _buffer = new List<GameEntity>(8);

    public RemoveMyNamespaceWatchedInNamespaceChangedGameSystem(Contexts contexts) {
        _group = contexts.game.GetGroup(GameMatcher.MyNamespaceWatchedInNamespaceChanged);
    }

    public void Cleanup() {
        foreach (var e in _group.GetEntities(_buffer)) {
            e.isMyNamespaceWatchedInNamespaceChanged = false;
        }
    }
}

