// <auto-generated/>
public sealed class GameCleanupSystems : Feature {

    public GameCleanupSystems(Contexts contexts) {
        Add(new DestroyCleanupDestroyGameSystem(contexts));
        Add(new RemoveCleanupRemoveGameSystem(contexts));
    }
}

