// <auto-generated/>
public partial class GameEntity {

    static readonly CleanupDestroyComponent cleanupDestroyComponent = new CleanupDestroyComponent();

    public bool isCleanupDestroy {
        get { return HasComponent(GameComponentsLookup.CleanupDestroy); }
        set {
            if (value != isCleanupDestroy) {
                var index = GameComponentsLookup.CleanupDestroy;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : cleanupDestroyComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherCleanupDestroy;

    public static Entitas.IMatcher<GameEntity> CleanupDestroy {
        get {
            if (_matcherCleanupDestroy == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.CleanupDestroy);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherCleanupDestroy = matcher;
            }

            return _matcherCleanupDestroy;
        }
    }
}

