// <auto-generated/>
using System.Collections.Generic;
using Entitas;

public sealed class RemoveCleanupRemoveGameSystem : ICleanupSystem {

    readonly IGroup<GameEntity> _group;
    readonly List<GameEntity> _buffer = new List<GameEntity>();

    public RemoveCleanupRemoveGameSystem(Contexts contexts) {
        _group = contexts.game.GetGroup(GameMatcher.CleanupRemove);
    }

    public void Cleanup() {
        foreach (var e in _group.GetEntities(_buffer)) {
            e.isCleanupRemove = false;
        }
    }
}

