// <auto-generated/>
public partial class GameEntity {

    static readonly WatchedFlagComponent watchedFlagComponent = new WatchedFlagComponent();

    public bool isWatchedFlag {
        get { return HasComponent(GameComponentsLookup.WatchedFlag); }
        set {
            if (value != isWatchedFlag) {
                var index = GameComponentsLookup.WatchedFlag;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : watchedFlagComponent;

                    AddComponent(index, component);
                    isWatchedFlagChanged = true;
                } else {
                    RemoveComponent(index);
                    isWatchedFlagChanged = true;
                }
            }
        }
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherWatchedFlag;

    public static Entitas.IMatcher<GameEntity> WatchedFlag {
        get {
            if (_matcherWatchedFlag == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.WatchedFlag);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherWatchedFlag = matcher;
            }

            return _matcherWatchedFlag;
        }
    }
}

