// <auto-generated/>
public static class GameComponentsLookup {

    public const int Array3d = 0;
    public const int CleanupDestroy = 1;
    public const int CleanupRemove = 2;
    public const int GeneratedContext = 3;
    public const int Inherited = 4;
    public const int MultiplePrimaryEntityIndices = 5;
    public const int MyNamespaceEntityIndexNoContext = 6;
    public const int MyNamespaceWatchedInNamespace = 7;
    public const int MyNamespaceWatchedInNamespaceChanged = 8;
    public const int NoContext = 9;
    public const int Parent = 10;
    public const int PrimaryEntityIndex = 11;
    public const int WatchedFlagChanged = 12;
    public const int WatchedFlag = 13;
    public const int WatchedValueChanged = 14;
    public const int WatchedValue = 15;

    public const int TotalComponents = 16;

    public static readonly string[] componentNames = {
        "Array3d",
        "CleanupDestroy",
        "CleanupRemove",
        "GeneratedContext",
        "Inherited",
        "MultiplePrimaryEntityIndices",
        "MyNamespaceEntityIndexNoContext",
        "MyNamespaceWatchedInNamespace",
        "MyNamespaceWatchedInNamespaceChanged",
        "NoContext",
        "Parent",
        "PrimaryEntityIndex",
        "WatchedFlagChanged",
        "WatchedFlag",
        "WatchedValueChanged",
        "WatchedValue"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(Array3dComponent),
        typeof(CleanupDestroyComponent),
        typeof(CleanupRemoveComponent),
        typeof(GeneratedContextComponent),
        typeof(InheritedComponent),
        typeof(MultiplePrimaryEntityIndicesComponent),
        typeof(My.Namespace.EntityIndexNoContextComponent),
        typeof(MyNamespace.WatchedInNamespaceComponent),
        typeof(MyNamespaceWatchedInNamespaceChanged),
        typeof(NoContextComponent),
        typeof(ParentComponent),
        typeof(PrimaryEntityIndexComponent),
        typeof(WatchedFlagChanged),
        typeof(WatchedFlagComponent),
        typeof(WatchedValueChanged),
        typeof(WatchedValueComponent)
    };
}

