// <auto-generated/>
public sealed class GameWatchedCleanupSystems : Feature {

    public GameWatchedCleanupSystems(Contexts contexts) {
        Add(new RemoveMyNamespaceWatchedInNamespaceChangedGameSystem(contexts));
        Add(new RemoveWatchedFlagChangedGameSystem(contexts));
        Add(new RemoveWatchedValueChangedGameSystem(contexts));
    }
}

