// <auto-generated/>
public sealed partial class GameEntity {

    /// <summary>
    /// Indicates whether the component with the given ID has changed since the last network tick.
    /// </summary>
    public bool HasChanged(int lookupComponentId) => lookupComponentId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespace => isMyNamespaceWatchedInNamespaceChanged,
        GameComponentsLookup.WatchedFlag => isWatchedFlagChanged,
        GameComponentsLookup.WatchedValue => isWatchedValueChanged,
        _ => false
    };

    /// <summary>
    /// Indicates whether the given component ID corresponds to a "changed" flag component, like `CurrentHealthChanged`.
    /// </summary>
    public bool ComponentIsChangedFlag(int lookupComponentId) => lookupComponentId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged => true,
        GameComponentsLookup.WatchedFlagChanged => true,
        GameComponentsLookup.WatchedValueChanged => true,
        _ => false
    };

    /// <summary>
    /// Given a "changed" flag component ID, returns the original component ID it corresponds to.
    /// </summary>
    public int GetOriginalComponentIdFromChangeFlag(int lookupComponentId) => lookupComponentId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged => GameComponentsLookup.MyNamespaceWatchedInNamespace,
        GameComponentsLookup.WatchedFlagChanged => GameComponentsLookup.WatchedFlag,
        GameComponentsLookup.WatchedValueChanged => GameComponentsLookup.WatchedValue,
        _ => throw new System.ArgumentException($"Component ID {lookupComponentId} is not a recognized 'changed' flag component.")
    };

    /// <summary>
    /// Indicates whether the component with the given ID is a watched component.
    /// </summary>
    public bool IsWatchedComponent(int lookupComponentId) => lookupComponentId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespace => true,
        GameComponentsLookup.WatchedFlag => true,
        GameComponentsLookup.WatchedValue => true,
        _ => false
    };

    /// <summary>
    /// Given a component ID, returns the corresponding "changed" flag component ID.
    /// </summary>
    public int GetChangedFlagIdOf(int lookupComponentId) => lookupComponentId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespace => GameComponentsLookup.MyNamespaceWatchedInNamespaceChanged,
        GameComponentsLookup.WatchedFlag => GameComponentsLookup.WatchedFlagChanged,
        GameComponentsLookup.WatchedValue => GameComponentsLookup.WatchedValueChanged,
        _ => throw new System.ArgumentException($"Component ID {lookupComponentId} does not have a corresponding 'changed' flag component.")
    };

    /// <summary>
    /// Given a component ID, returns the corresponding "changed" flag component Type.
    /// </summary>
    public System.Type GetChangeFlagTypeOf(int changeComponentTypeId) => changeComponentTypeId switch {
        GameComponentsLookup.MyNamespaceWatchedInNamespace => typeof(global::MyNamespaceWatchedInNamespaceChanged),
        GameComponentsLookup.WatchedFlag => typeof(global::WatchedFlagChanged),
        GameComponentsLookup.WatchedValue => typeof(global::WatchedValueChanged),
        _ => throw new System.ArgumentException($"Component ID {changeComponentTypeId} does not have a corresponding 'changed' flag component type.")
    };
}

