// <auto-generated/>
public partial class GameEntity {

    public Array3dComponent array3d { get { return (Array3dComponent)GetComponent(GameComponentsLookup.Array3d); } }
    public bool hasArray3d { get { return HasComponent(GameComponentsLookup.Array3d); } }

    public GameEntity AddArray3d(int[,,] newValue) {
        var index = GameComponentsLookup.Array3d;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Array3dComponent)componentPool.Pop()
            : new Array3dComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public GameEntity ReplaceArray3d(int[,,] newValue) {
        var index = GameComponentsLookup.Array3d;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Array3dComponent)componentPool.Pop()
            : new Array3dComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public GameEntity RemoveArray3d() {
        RemoveComponent(GameComponentsLookup.Array3d);

        return this;
    }


    public GameEntity SafeRemoveArray3d() {
        if (hasArray3d)
        {
            RemoveComponent(GameComponentsLookup.Array3d);
        }

        return this;
    }
}

public sealed partial class GameMatcher {

    static Entitas.IMatcher<GameEntity> _matcherArray3d;

    public static Entitas.IMatcher<GameEntity> Array3d {
        get {
            if (_matcherArray3d == null) {
                var matcher = (Entitas.Matcher<GameEntity>)Entitas.Matcher<GameEntity>.AllOf(GameComponentsLookup.Array3d);
                matcher.componentNames = GameComponentsLookup.componentNames;
                _matcherArray3d = matcher;
            }

            return _matcherArray3d;
        }
    }
}

