// <auto-generated/>
public partial class Test2Entity {

    public Test2AnyMultipleEventsStandardEventListenerComponent test2AnyMultipleEventsStandardEventListener { get { return (Test2AnyMultipleEventsStandardEventListenerComponent)GetComponent(Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener); } }
    public bool hasTest2AnyMultipleEventsStandardEventListener { get { return HasComponent(Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener); } }

    public Test2Entity AddTest2AnyMultipleEventsStandardEventListener(System.Collections.Generic.List<ITest2AnyMultipleEventsStandardEventListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyMultipleEventsStandardEventListenerComponent)componentPool.Pop()
            : new Test2AnyMultipleEventsStandardEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceTest2AnyMultipleEventsStandardEventListener(System.Collections.Generic.List<ITest2AnyMultipleEventsStandardEventListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyMultipleEventsStandardEventListenerComponent)componentPool.Pop()
            : new Test2AnyMultipleEventsStandardEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveTest2AnyMultipleEventsStandardEventListener() {
        RemoveComponent(Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener);

        return this;
    }


    public Test2Entity SafeRemoveTest2AnyMultipleEventsStandardEventListener() {
        if (hasTest2AnyMultipleEventsStandardEventListener)
        {
            RemoveComponent(Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener);
        }

        return this;
    }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherTest2AnyMultipleEventsStandardEventListener;

    public static Entitas.IMatcher<Test2Entity> Test2AnyMultipleEventsStandardEventListener {
        get {
            if (_matcherTest2AnyMultipleEventsStandardEventListener == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.Test2AnyMultipleEventsStandardEventListener);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherTest2AnyMultipleEventsStandardEventListener = matcher;
            }

            return _matcherTest2AnyMultipleEventsStandardEventListener;
        }
    }
}

public partial class Test2Entity {

    public void AddTest2AnyMultipleEventsStandardEventListener(ITest2AnyMultipleEventsStandardEventListener value) {
        var listeners = hasTest2AnyMultipleEventsStandardEventListener
            ? test2AnyMultipleEventsStandardEventListener.value
            : new System.Collections.Generic.List<ITest2AnyMultipleEventsStandardEventListener>();
        listeners.Add(value);
        ReplaceTest2AnyMultipleEventsStandardEventListener(listeners);
    }

    public void RemoveTest2AnyMultipleEventsStandardEventListener(ITest2AnyMultipleEventsStandardEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = test2AnyMultipleEventsStandardEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTest2AnyMultipleEventsStandardEventListener();
        } else {
            ReplaceTest2AnyMultipleEventsStandardEventListener(listeners);
        }
    }
}

