// <auto-generated/>
public partial class TestEntity {

    public AnyMixedEventListenerComponent anyMixedEventListener { get { return (AnyMixedEventListenerComponent)GetComponent(TestComponentsLookup.AnyMixedEventListener); } }
    public bool hasAnyMixedEventListener { get { return HasComponent(TestComponentsLookup.AnyMixedEventListener); } }

    public TestEntity AddAnyMixedEventListener(System.Collections.Generic.List<IAnyMixedEventListener> newValue) {
        var index = TestComponentsLookup.AnyMixedEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyMixedEventListenerComponent)componentPool.Pop()
            : new AnyMixedEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceAnyMixedEventListener(System.Collections.Generic.List<IAnyMixedEventListener> newValue) {
        var index = TestComponentsLookup.AnyMixedEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyMixedEventListenerComponent)componentPool.Pop()
            : new AnyMixedEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveAnyMixedEventListener() {
        RemoveComponent(TestComponentsLookup.AnyMixedEventListener);

        return this;
    }


    public TestEntity SafeRemoveAnyMixedEventListener() {
        if (hasAnyMixedEventListener)
        {
            RemoveComponent(TestComponentsLookup.AnyMixedEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherAnyMixedEventListener;

    public static Entitas.IMatcher<TestEntity> AnyMixedEventListener {
        get {
            if (_matcherAnyMixedEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.AnyMixedEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherAnyMixedEventListener = matcher;
            }

            return _matcherAnyMixedEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddAnyMixedEventListener(IAnyMixedEventListener value) {
        var listeners = hasAnyMixedEventListener
            ? anyMixedEventListener.value
            : new System.Collections.Generic.List<IAnyMixedEventListener>();
        listeners.Add(value);
        ReplaceAnyMixedEventListener(listeners);
    }

    public void RemoveAnyMixedEventListener(IAnyMixedEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = anyMixedEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveAnyMixedEventListener();
        } else {
            ReplaceAnyMixedEventListener(listeners);
        }
    }
}

