// <auto-generated/>
public partial class Test2Entity {

    public EventToGenerateComponent eventToGenerate { get { return (EventToGenerateComponent)GetComponent(Test2ComponentsLookup.EventToGenerate); } }
    public bool hasEventToGenerate { get { return HasComponent(Test2ComponentsLookup.EventToGenerate); } }

    public Test2Entity AddEventToGenerate(My.Namespace.EventToGenerate newValue) {
        var index = Test2ComponentsLookup.EventToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventToGenerateComponent)componentPool.Pop()
            : new EventToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceEventToGenerate(My.Namespace.EventToGenerate newValue) {
        var index = Test2ComponentsLookup.EventToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventToGenerateComponent)componentPool.Pop()
            : new EventToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveEventToGenerate() {
        RemoveComponent(Test2ComponentsLookup.EventToGenerate);

        return this;
    }


    public Test2Entity SafeRemoveEventToGenerate() {
        if (hasEventToGenerate)
        {
            RemoveComponent(Test2ComponentsLookup.EventToGenerate);
        }

        return this;
    }
}

public partial class Test2Entity : IEventToGenerateEntity {
    void IEventToGenerateEntity.AddEventToGenerate(My.Namespace.EventToGenerate newValue) { AddEventToGenerate(newValue); }
    void IEventToGenerateEntity.ReplaceEventToGenerate(My.Namespace.EventToGenerate newValue) { ReplaceEventToGenerate(newValue); }
    void IEventToGenerateEntity.RemoveEventToGenerate() { RemoveEventToGenerate(); }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherEventToGenerate;

    public static Entitas.IMatcher<Test2Entity> EventToGenerate {
        get {
            if (_matcherEventToGenerate == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.EventToGenerate);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherEventToGenerate = matcher;
            }

            return _matcherEventToGenerate;
        }
    }
}

