// <auto-generated/>
public partial class TestEntity {

    public ComponentWithProperties componentWithProperties { get { return (ComponentWithProperties)GetComponent(TestComponentsLookup.ComponentWithProperties); } }
    public bool hasComponentWithProperties { get { return HasComponent(TestComponentsLookup.ComponentWithProperties); } }

    public TestEntity AddComponentWithProperties(string newPublicProperty) {
        var index = TestComponentsLookup.ComponentWithProperties;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithProperties)componentPool.Pop()
            : new ComponentWithProperties();
        component.publicProperty = newPublicProperty;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceComponentWithProperties(string newPublicProperty) {
        var index = TestComponentsLookup.ComponentWithProperties;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithProperties)componentPool.Pop()
            : new ComponentWithProperties();
        component.publicProperty = newPublicProperty;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveComponentWithProperties() {
        RemoveComponent(TestComponentsLookup.ComponentWithProperties);

        return this;
    }


    public TestEntity SafeRemoveComponentWithProperties() {
        if (hasComponentWithProperties)
        {
            RemoveComponent(TestComponentsLookup.ComponentWithProperties);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherComponentWithProperties;

    public static Entitas.IMatcher<TestEntity> ComponentWithProperties {
        get {
            if (_matcherComponentWithProperties == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.ComponentWithProperties);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherComponentWithProperties = matcher;
            }

            return _matcherComponentWithProperties;
        }
    }
}

