// <auto-generated/>
public partial class TestEntity {

    public StandardEntityEventComponent standardEntityEvent { get { return (StandardEntityEventComponent)GetComponent(TestComponentsLookup.StandardEntityEvent); } }
    public bool hasStandardEntityEvent { get { return HasComponent(TestComponentsLookup.StandardEntityEvent); } }

    public TestEntity AddStandardEntityEvent(string newValue) {
        var index = TestComponentsLookup.StandardEntityEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEntityEventComponent)componentPool.Pop()
            : new StandardEntityEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceStandardEntityEvent(string newValue) {
        var index = TestComponentsLookup.StandardEntityEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEntityEventComponent)componentPool.Pop()
            : new StandardEntityEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveStandardEntityEvent() {
        RemoveComponent(TestComponentsLookup.StandardEntityEvent);

        return this;
    }


    public TestEntity SafeRemoveStandardEntityEvent() {
        if (hasStandardEntityEvent)
        {
            RemoveComponent(TestComponentsLookup.StandardEntityEvent);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherStandardEntityEvent;

    public static Entitas.IMatcher<TestEntity> StandardEntityEvent {
        get {
            if (_matcherStandardEntityEvent == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.StandardEntityEvent);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherStandardEntityEvent = matcher;
            }

            return _matcherStandardEntityEvent;
        }
    }
}

