// <auto-generated/>
public partial class TestEntity {

    public StandardEventComponent standardEvent { get { return (StandardEventComponent)GetComponent(TestComponentsLookup.StandardEvent); } }
    public bool hasStandardEvent { get { return HasComponent(TestComponentsLookup.StandardEvent); } }

    public TestEntity AddStandardEvent(string newValue) {
        var index = TestComponentsLookup.StandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEventComponent)componentPool.Pop()
            : new StandardEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceStandardEvent(string newValue) {
        var index = TestComponentsLookup.StandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEventComponent)componentPool.Pop()
            : new StandardEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveStandardEvent() {
        RemoveComponent(TestComponentsLookup.StandardEvent);

        return this;
    }


    public TestEntity SafeRemoveStandardEvent() {
        if (hasStandardEvent)
        {
            RemoveComponent(TestComponentsLookup.StandardEvent);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherStandardEvent;

    public static Entitas.IMatcher<TestEntity> StandardEvent {
        get {
            if (_matcherStandardEvent == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.StandardEvent);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherStandardEvent = matcher;
            }

            return _matcherStandardEvent;
        }
    }
}

