// <auto-generated/>
public partial class TestEntity {

    public MultipleContextStandardEventComponent multipleContextStandardEvent { get { return (MultipleContextStandardEventComponent)GetComponent(TestComponentsLookup.MultipleContextStandardEvent); } }
    public bool hasMultipleContextStandardEvent { get { return HasComponent(TestComponentsLookup.MultipleContextStandardEvent); } }

    public TestEntity AddMultipleContextStandardEvent(string newValue) {
        var index = TestComponentsLookup.MultipleContextStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleContextStandardEventComponent)componentPool.Pop()
            : new MultipleContextStandardEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMultipleContextStandardEvent(string newValue) {
        var index = TestComponentsLookup.MultipleContextStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleContextStandardEventComponent)componentPool.Pop()
            : new MultipleContextStandardEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMultipleContextStandardEvent() {
        RemoveComponent(TestComponentsLookup.MultipleContextStandardEvent);

        return this;
    }


    public TestEntity SafeRemoveMultipleContextStandardEvent() {
        if (hasMultipleContextStandardEvent)
        {
            RemoveComponent(TestComponentsLookup.MultipleContextStandardEvent);
        }

        return this;
    }
}

public partial class TestEntity : IMultipleContextStandardEventEntity {
    void IMultipleContextStandardEventEntity.AddMultipleContextStandardEvent(string newValue) { AddMultipleContextStandardEvent(newValue); }
    void IMultipleContextStandardEventEntity.ReplaceMultipleContextStandardEvent(string newValue) { ReplaceMultipleContextStandardEvent(newValue); }
    void IMultipleContextStandardEventEntity.RemoveMultipleContextStandardEvent() { RemoveMultipleContextStandardEvent(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMultipleContextStandardEvent;

    public static Entitas.IMatcher<TestEntity> MultipleContextStandardEvent {
        get {
            if (_matcherMultipleContextStandardEvent == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MultipleContextStandardEvent);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMultipleContextStandardEvent = matcher;
            }

            return _matcherMultipleContextStandardEvent;
        }
    }
}

