// <auto-generated/>
public partial class TestEntity {

    public MultipleEventsStandardEventComponent multipleEventsStandardEvent { get { return (MultipleEventsStandardEventComponent)GetComponent(TestComponentsLookup.MultipleEventsStandardEvent); } }
    public bool hasMultipleEventsStandardEvent { get { return HasComponent(TestComponentsLookup.MultipleEventsStandardEvent); } }

    public TestEntity AddMultipleEventsStandardEvent(string newValue) {
        var index = TestComponentsLookup.MultipleEventsStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleEventsStandardEventComponent)componentPool.Pop()
            : new MultipleEventsStandardEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMultipleEventsStandardEvent(string newValue) {
        var index = TestComponentsLookup.MultipleEventsStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleEventsStandardEventComponent)componentPool.Pop()
            : new MultipleEventsStandardEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMultipleEventsStandardEvent() {
        RemoveComponent(TestComponentsLookup.MultipleEventsStandardEvent);

        return this;
    }


    public TestEntity SafeRemoveMultipleEventsStandardEvent() {
        if (hasMultipleEventsStandardEvent)
        {
            RemoveComponent(TestComponentsLookup.MultipleEventsStandardEvent);
        }

        return this;
    }
}

public partial class TestEntity : IMultipleEventsStandardEventEntity {
    void IMultipleEventsStandardEventEntity.AddMultipleEventsStandardEvent(string newValue) { AddMultipleEventsStandardEvent(newValue); }
    void IMultipleEventsStandardEventEntity.ReplaceMultipleEventsStandardEvent(string newValue) { ReplaceMultipleEventsStandardEvent(newValue); }
    void IMultipleEventsStandardEventEntity.RemoveMultipleEventsStandardEvent() { RemoveMultipleEventsStandardEvent(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMultipleEventsStandardEvent;

    public static Entitas.IMatcher<TestEntity> MultipleEventsStandardEvent {
        get {
            if (_matcherMultipleEventsStandardEvent == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MultipleEventsStandardEvent);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMultipleEventsStandardEvent = matcher;
            }

            return _matcherMultipleEventsStandardEvent;
        }
    }
}

