// <auto-generated/>
public partial class TestEntity {

    public MixedEventListenerComponent mixedEventListener { get { return (MixedEventListenerComponent)GetComponent(TestComponentsLookup.MixedEventListener); } }
    public bool hasMixedEventListener { get { return HasComponent(TestComponentsLookup.MixedEventListener); } }

    public TestEntity AddMixedEventListener(System.Collections.Generic.List<IMixedEventListener> newValue) {
        var index = TestComponentsLookup.MixedEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MixedEventListenerComponent)componentPool.Pop()
            : new MixedEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMixedEventListener(System.Collections.Generic.List<IMixedEventListener> newValue) {
        var index = TestComponentsLookup.MixedEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MixedEventListenerComponent)componentPool.Pop()
            : new MixedEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMixedEventListener() {
        RemoveComponent(TestComponentsLookup.MixedEventListener);

        return this;
    }


    public TestEntity SafeRemoveMixedEventListener() {
        if (hasMixedEventListener)
        {
            RemoveComponent(TestComponentsLookup.MixedEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMixedEventListener;

    public static Entitas.IMatcher<TestEntity> MixedEventListener {
        get {
            if (_matcherMixedEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MixedEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMixedEventListener = matcher;
            }

            return _matcherMixedEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddMixedEventListener(IMixedEventListener value) {
        var listeners = hasMixedEventListener
            ? mixedEventListener.value
            : new System.Collections.Generic.List<IMixedEventListener>();
        listeners.Add(value);
        ReplaceMixedEventListener(listeners);
    }

    public void RemoveMixedEventListener(IMixedEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = mixedEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveMixedEventListener();
        } else {
            ReplaceMixedEventListener(listeners);
        }
    }
}

