// <auto-generated/>
public partial class TestEntity {

    public Test2ContextComponent test2Context { get { return (Test2ContextComponent)GetComponent(TestComponentsLookup.Test2Context); } }
    public bool hasTest2Context { get { return HasComponent(TestComponentsLookup.Test2Context); } }

    public TestEntity AddTest2Context(string newValue) {
        var index = TestComponentsLookup.Test2Context;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2ContextComponent)componentPool.Pop()
            : new Test2ContextComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceTest2Context(string newValue) {
        var index = TestComponentsLookup.Test2Context;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2ContextComponent)componentPool.Pop()
            : new Test2ContextComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveTest2Context() {
        RemoveComponent(TestComponentsLookup.Test2Context);

        return this;
    }


    public TestEntity SafeRemoveTest2Context() {
        if (hasTest2Context)
        {
            RemoveComponent(TestComponentsLookup.Test2Context);
        }

        return this;
    }
}

public partial class TestEntity : ITest2ContextEntity {
    void ITest2ContextEntity.AddTest2Context(string newValue) { AddTest2Context(newValue); }
    void ITest2ContextEntity.ReplaceTest2Context(string newValue) { ReplaceTest2Context(newValue); }
    void ITest2ContextEntity.RemoveTest2Context() { RemoveTest2Context(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherTest2Context;

    public static Entitas.IMatcher<TestEntity> Test2Context {
        get {
            if (_matcherTest2Context == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.Test2Context);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherTest2Context = matcher;
            }

            return _matcherTest2Context;
        }
    }
}

