// <auto-generated/>
public partial class TestEntity {

    public NewCustomNameComponent1Component newCustomNameComponent1 { get { return (NewCustomNameComponent1Component)GetComponent(TestComponentsLookup.NewCustomNameComponent1); } }
    public bool hasNewCustomNameComponent1 { get { return HasComponent(TestComponentsLookup.NewCustomNameComponent1); } }

    public TestEntity AddNewCustomNameComponent1(CustomName newValue) {
        var index = TestComponentsLookup.NewCustomNameComponent1;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NewCustomNameComponent1Component)componentPool.Pop()
            : new NewCustomNameComponent1Component();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceNewCustomNameComponent1(CustomName newValue) {
        var index = TestComponentsLookup.NewCustomNameComponent1;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NewCustomNameComponent1Component)componentPool.Pop()
            : new NewCustomNameComponent1Component();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveNewCustomNameComponent1() {
        RemoveComponent(TestComponentsLookup.NewCustomNameComponent1);

        return this;
    }


    public TestEntity SafeRemoveNewCustomNameComponent1() {
        if (hasNewCustomNameComponent1)
        {
            RemoveComponent(TestComponentsLookup.NewCustomNameComponent1);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherNewCustomNameComponent1;

    public static Entitas.IMatcher<TestEntity> NewCustomNameComponent1 {
        get {
            if (_matcherNewCustomNameComponent1 == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.NewCustomNameComponent1);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherNewCustomNameComponent1 = matcher;
            }

            return _matcherNewCustomNameComponent1;
        }
    }
}

