// <auto-generated/>
public partial class TestEntity {

    public MixedEventComponent mixedEvent { get { return (MixedEventComponent)GetComponent(TestComponentsLookup.MixedEvent); } }
    public bool hasMixedEvent { get { return HasComponent(TestComponentsLookup.MixedEvent); } }

    public TestEntity AddMixedEvent(string newValue) {
        var index = TestComponentsLookup.MixedEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MixedEventComponent)componentPool.Pop()
            : new MixedEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMixedEvent(string newValue) {
        var index = TestComponentsLookup.MixedEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MixedEventComponent)componentPool.Pop()
            : new MixedEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMixedEvent() {
        RemoveComponent(TestComponentsLookup.MixedEvent);

        return this;
    }


    public TestEntity SafeRemoveMixedEvent() {
        if (hasMixedEvent)
        {
            RemoveComponent(TestComponentsLookup.MixedEvent);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMixedEvent;

    public static Entitas.IMatcher<TestEntity> MixedEvent {
        get {
            if (_matcherMixedEvent == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MixedEvent);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMixedEvent = matcher;
            }

            return _matcherMixedEvent;
        }
    }
}

