// <auto-generated/>
public partial class TestEntity {

    public FlagEntityEventListenerComponent flagEntityEventListener { get { return (FlagEntityEventListenerComponent)GetComponent(TestComponentsLookup.FlagEntityEventListener); } }
    public bool hasFlagEntityEventListener { get { return HasComponent(TestComponentsLookup.FlagEntityEventListener); } }

    public TestEntity AddFlagEntityEventListener(System.Collections.Generic.List<IFlagEntityEventListener> newValue) {
        var index = TestComponentsLookup.FlagEntityEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (FlagEntityEventListenerComponent)componentPool.Pop()
            : new FlagEntityEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceFlagEntityEventListener(System.Collections.Generic.List<IFlagEntityEventListener> newValue) {
        var index = TestComponentsLookup.FlagEntityEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (FlagEntityEventListenerComponent)componentPool.Pop()
            : new FlagEntityEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveFlagEntityEventListener() {
        RemoveComponent(TestComponentsLookup.FlagEntityEventListener);

        return this;
    }


    public TestEntity SafeRemoveFlagEntityEventListener() {
        if (hasFlagEntityEventListener)
        {
            RemoveComponent(TestComponentsLookup.FlagEntityEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherFlagEntityEventListener;

    public static Entitas.IMatcher<TestEntity> FlagEntityEventListener {
        get {
            if (_matcherFlagEntityEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.FlagEntityEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherFlagEntityEventListener = matcher;
            }

            return _matcherFlagEntityEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddFlagEntityEventListener(IFlagEntityEventListener value) {
        var listeners = hasFlagEntityEventListener
            ? flagEntityEventListener.value
            : new System.Collections.Generic.List<IFlagEntityEventListener>();
        listeners.Add(value);
        ReplaceFlagEntityEventListener(listeners);
    }

    public void RemoveFlagEntityEventListener(IFlagEntityEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = flagEntityEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveFlagEntityEventListener();
        } else {
            ReplaceFlagEntityEventListener(listeners);
        }
    }
}

