// <auto-generated/>
public partial class TestEntity {

    public NameAgeComponent nameAge { get { return (NameAgeComponent)GetComponent(TestComponentsLookup.NameAge); } }
    public bool hasNameAge { get { return HasComponent(TestComponentsLookup.NameAge); } }

    public TestEntity AddNameAge(string newName, int newAge) {
        var index = TestComponentsLookup.NameAge;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NameAgeComponent)componentPool.Pop()
            : new NameAgeComponent();
        component.name = newName;
        component.age = newAge;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceNameAge(string newName, int newAge) {
        var index = TestComponentsLookup.NameAge;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NameAgeComponent)componentPool.Pop()
            : new NameAgeComponent();
        component.name = newName;
        component.age = newAge;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveNameAge() {
        RemoveComponent(TestComponentsLookup.NameAge);

        return this;
    }


    public TestEntity SafeRemoveNameAge() {
        if (hasNameAge)
        {
            RemoveComponent(TestComponentsLookup.NameAge);
        }

        return this;
    }
}

public partial class TestEntity : INameAgeEntity {
    void INameAgeEntity.AddNameAge(string newName, int newAge) { AddNameAge(newName, newAge); }
    void INameAgeEntity.ReplaceNameAge(string newName, int newAge) { ReplaceNameAge(newName, newAge); }
    void INameAgeEntity.RemoveNameAge() { RemoveNameAge(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherNameAge;

    public static Entitas.IMatcher<TestEntity> NameAge {
        get {
            if (_matcherNameAge == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.NameAge);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherNameAge = matcher;
            }

            return _matcherNameAge;
        }
    }
}

