// <auto-generated/>
public partial class TestEntity {

    public TestAnyEventToGenerateListenerComponent testAnyEventToGenerateListener { get { return (TestAnyEventToGenerateListenerComponent)GetComponent(TestComponentsLookup.TestAnyEventToGenerateListener); } }
    public bool hasTestAnyEventToGenerateListener { get { return HasComponent(TestComponentsLookup.TestAnyEventToGenerateListener); } }

    public TestEntity AddTestAnyEventToGenerateListener(System.Collections.Generic.List<ITestAnyEventToGenerateListener> newValue) {
        var index = TestComponentsLookup.TestAnyEventToGenerateListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestAnyEventToGenerateListenerComponent)componentPool.Pop()
            : new TestAnyEventToGenerateListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceTestAnyEventToGenerateListener(System.Collections.Generic.List<ITestAnyEventToGenerateListener> newValue) {
        var index = TestComponentsLookup.TestAnyEventToGenerateListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestAnyEventToGenerateListenerComponent)componentPool.Pop()
            : new TestAnyEventToGenerateListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveTestAnyEventToGenerateListener() {
        RemoveComponent(TestComponentsLookup.TestAnyEventToGenerateListener);

        return this;
    }


    public TestEntity SafeRemoveTestAnyEventToGenerateListener() {
        if (hasTestAnyEventToGenerateListener)
        {
            RemoveComponent(TestComponentsLookup.TestAnyEventToGenerateListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherTestAnyEventToGenerateListener;

    public static Entitas.IMatcher<TestEntity> TestAnyEventToGenerateListener {
        get {
            if (_matcherTestAnyEventToGenerateListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.TestAnyEventToGenerateListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherTestAnyEventToGenerateListener = matcher;
            }

            return _matcherTestAnyEventToGenerateListener;
        }
    }
}

public partial class TestEntity {

    public void AddTestAnyEventToGenerateListener(ITestAnyEventToGenerateListener value) {
        var listeners = hasTestAnyEventToGenerateListener
            ? testAnyEventToGenerateListener.value
            : new System.Collections.Generic.List<ITestAnyEventToGenerateListener>();
        listeners.Add(value);
        ReplaceTestAnyEventToGenerateListener(listeners);
    }

    public void RemoveTestAnyEventToGenerateListener(ITestAnyEventToGenerateListener value, bool removeComponentWhenEmpty = true) {
        var listeners = testAnyEventToGenerateListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTestAnyEventToGenerateListener();
        } else {
            ReplaceTestAnyEventToGenerateListener(listeners);
        }
    }
}

