// <auto-generated/>
public partial class TestEntity {

    public StandardEntityEventRemovedListenerComponent standardEntityEventRemovedListener { get { return (StandardEntityEventRemovedListenerComponent)GetComponent(TestComponentsLookup.StandardEntityEventRemovedListener); } }
    public bool hasStandardEntityEventRemovedListener { get { return HasComponent(TestComponentsLookup.StandardEntityEventRemovedListener); } }

    public TestEntity AddStandardEntityEventRemovedListener(System.Collections.Generic.List<IStandardEntityEventRemovedListener> newValue) {
        var index = TestComponentsLookup.StandardEntityEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEntityEventRemovedListenerComponent)componentPool.Pop()
            : new StandardEntityEventRemovedListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceStandardEntityEventRemovedListener(System.Collections.Generic.List<IStandardEntityEventRemovedListener> newValue) {
        var index = TestComponentsLookup.StandardEntityEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardEntityEventRemovedListenerComponent)componentPool.Pop()
            : new StandardEntityEventRemovedListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveStandardEntityEventRemovedListener() {
        RemoveComponent(TestComponentsLookup.StandardEntityEventRemovedListener);

        return this;
    }


    public TestEntity SafeRemoveStandardEntityEventRemovedListener() {
        if (hasStandardEntityEventRemovedListener)
        {
            RemoveComponent(TestComponentsLookup.StandardEntityEventRemovedListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherStandardEntityEventRemovedListener;

    public static Entitas.IMatcher<TestEntity> StandardEntityEventRemovedListener {
        get {
            if (_matcherStandardEntityEventRemovedListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.StandardEntityEventRemovedListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherStandardEntityEventRemovedListener = matcher;
            }

            return _matcherStandardEntityEventRemovedListener;
        }
    }
}

public partial class TestEntity {

    public void AddStandardEntityEventRemovedListener(IStandardEntityEventRemovedListener value) {
        var listeners = hasStandardEntityEventRemovedListener
            ? standardEntityEventRemovedListener.value
            : new System.Collections.Generic.List<IStandardEntityEventRemovedListener>();
        listeners.Add(value);
        ReplaceStandardEntityEventRemovedListener(listeners);
    }

    public void RemoveStandardEntityEventRemovedListener(IStandardEntityEventRemovedListener value, bool removeComponentWhenEmpty = true) {
        var listeners = standardEntityEventRemovedListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveStandardEntityEventRemovedListener();
        } else {
            ReplaceStandardEntityEventRemovedListener(listeners);
        }
    }
}

