// <auto-generated/>
public partial class Test2Entity {

    public MultipleEventsStandardEventComponent multipleEventsStandardEvent { get { return (MultipleEventsStandardEventComponent)GetComponent(Test2ComponentsLookup.MultipleEventsStandardEvent); } }
    public bool hasMultipleEventsStandardEvent { get { return HasComponent(Test2ComponentsLookup.MultipleEventsStandardEvent); } }

    public Test2Entity AddMultipleEventsStandardEvent(string newValue) {
        var index = Test2ComponentsLookup.MultipleEventsStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleEventsStandardEventComponent)componentPool.Pop()
            : new MultipleEventsStandardEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceMultipleEventsStandardEvent(string newValue) {
        var index = Test2ComponentsLookup.MultipleEventsStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleEventsStandardEventComponent)componentPool.Pop()
            : new MultipleEventsStandardEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveMultipleEventsStandardEvent() {
        RemoveComponent(Test2ComponentsLookup.MultipleEventsStandardEvent);

        return this;
    }


    public Test2Entity SafeRemoveMultipleEventsStandardEvent() {
        if (hasMultipleEventsStandardEvent)
        {
            RemoveComponent(Test2ComponentsLookup.MultipleEventsStandardEvent);
        }

        return this;
    }
}

public partial class Test2Entity : IMultipleEventsStandardEventEntity {
    void IMultipleEventsStandardEventEntity.AddMultipleEventsStandardEvent(string newValue) { AddMultipleEventsStandardEvent(newValue); }
    void IMultipleEventsStandardEventEntity.ReplaceMultipleEventsStandardEvent(string newValue) { ReplaceMultipleEventsStandardEvent(newValue); }
    void IMultipleEventsStandardEventEntity.RemoveMultipleEventsStandardEvent() { RemoveMultipleEventsStandardEvent(); }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherMultipleEventsStandardEvent;

    public static Entitas.IMatcher<Test2Entity> MultipleEventsStandardEvent {
        get {
            if (_matcherMultipleEventsStandardEvent == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.MultipleEventsStandardEvent);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherMultipleEventsStandardEvent = matcher;
            }

            return _matcherMultipleEventsStandardEvent;
        }
    }
}

