// <auto-generated/>
public partial class Test2Entity {

    public Test2MultipleEventsStandardEventRemovedListenerComponent test2MultipleEventsStandardEventRemovedListener { get { return (Test2MultipleEventsStandardEventRemovedListenerComponent)GetComponent(Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener); } }
    public bool hasTest2MultipleEventsStandardEventRemovedListener { get { return HasComponent(Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener); } }

    public Test2Entity AddTest2MultipleEventsStandardEventRemovedListener(System.Collections.Generic.List<ITest2MultipleEventsStandardEventRemovedListener> newValue) {
        var index = Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2MultipleEventsStandardEventRemovedListenerComponent)componentPool.Pop()
            : new Test2MultipleEventsStandardEventRemovedListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceTest2MultipleEventsStandardEventRemovedListener(System.Collections.Generic.List<ITest2MultipleEventsStandardEventRemovedListener> newValue) {
        var index = Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2MultipleEventsStandardEventRemovedListenerComponent)componentPool.Pop()
            : new Test2MultipleEventsStandardEventRemovedListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveTest2MultipleEventsStandardEventRemovedListener() {
        RemoveComponent(Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener);

        return this;
    }


    public Test2Entity SafeRemoveTest2MultipleEventsStandardEventRemovedListener() {
        if (hasTest2MultipleEventsStandardEventRemovedListener)
        {
            RemoveComponent(Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener);
        }

        return this;
    }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherTest2MultipleEventsStandardEventRemovedListener;

    public static Entitas.IMatcher<Test2Entity> Test2MultipleEventsStandardEventRemovedListener {
        get {
            if (_matcherTest2MultipleEventsStandardEventRemovedListener == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.Test2MultipleEventsStandardEventRemovedListener);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherTest2MultipleEventsStandardEventRemovedListener = matcher;
            }

            return _matcherTest2MultipleEventsStandardEventRemovedListener;
        }
    }
}

public partial class Test2Entity {

    public void AddTest2MultipleEventsStandardEventRemovedListener(ITest2MultipleEventsStandardEventRemovedListener value) {
        var listeners = hasTest2MultipleEventsStandardEventRemovedListener
            ? test2MultipleEventsStandardEventRemovedListener.value
            : new System.Collections.Generic.List<ITest2MultipleEventsStandardEventRemovedListener>();
        listeners.Add(value);
        ReplaceTest2MultipleEventsStandardEventRemovedListener(listeners);
    }

    public void RemoveTest2MultipleEventsStandardEventRemovedListener(ITest2MultipleEventsStandardEventRemovedListener value, bool removeComponentWhenEmpty = true) {
        var listeners = test2MultipleEventsStandardEventRemovedListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTest2MultipleEventsStandardEventRemovedListener();
        } else {
            ReplaceTest2MultipleEventsStandardEventRemovedListener(listeners);
        }
    }
}

