// <auto-generated/>
public partial class Test2Entity {

    public My.Namespace.EntityIndexComponent myNamespaceEntityIndex { get { return (My.Namespace.EntityIndexComponent)GetComponent(Test2ComponentsLookup.MyNamespaceEntityIndex); } }
    public bool hasMyNamespaceEntityIndex { get { return HasComponent(Test2ComponentsLookup.MyNamespaceEntityIndex); } }

    public Test2Entity AddMyNamespaceEntityIndex(string newValue) {
        var index = Test2ComponentsLookup.MyNamespaceEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.EntityIndexComponent)componentPool.Pop()
            : new My.Namespace.EntityIndexComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceMyNamespaceEntityIndex(string newValue) {
        var index = Test2ComponentsLookup.MyNamespaceEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.EntityIndexComponent)componentPool.Pop()
            : new My.Namespace.EntityIndexComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveMyNamespaceEntityIndex() {
        RemoveComponent(Test2ComponentsLookup.MyNamespaceEntityIndex);

        return this;
    }


    public Test2Entity SafeRemoveMyNamespaceEntityIndex() {
        if (hasMyNamespaceEntityIndex)
        {
            RemoveComponent(Test2ComponentsLookup.MyNamespaceEntityIndex);
        }

        return this;
    }
}

public partial class Test2Entity : IMyNamespaceEntityIndexEntity {
    void IMyNamespaceEntityIndexEntity.AddMyNamespaceEntityIndex(string newValue) { AddMyNamespaceEntityIndex(newValue); }
    void IMyNamespaceEntityIndexEntity.ReplaceMyNamespaceEntityIndex(string newValue) { ReplaceMyNamespaceEntityIndex(newValue); }
    void IMyNamespaceEntityIndexEntity.RemoveMyNamespaceEntityIndex() { RemoveMyNamespaceEntityIndex(); }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherMyNamespaceEntityIndex;

    public static Entitas.IMatcher<Test2Entity> MyNamespaceEntityIndex {
        get {
            if (_matcherMyNamespaceEntityIndex == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.MyNamespaceEntityIndex);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherMyNamespaceEntityIndex = matcher;
            }

            return _matcherMyNamespaceEntityIndex;
        }
    }
}

