// <auto-generated/>
public partial class TestEntity {

    public ClassToGenerateComponent classToGenerate { get { return (ClassToGenerateComponent)GetComponent(TestComponentsLookup.ClassToGenerate); } }
    public bool hasClassToGenerate { get { return HasComponent(TestComponentsLookup.ClassToGenerate); } }

    public TestEntity AddClassToGenerate(My.Namespace.ClassToGenerate newValue) {
        var index = TestComponentsLookup.ClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassToGenerateComponent)componentPool.Pop()
            : new ClassToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceClassToGenerate(My.Namespace.ClassToGenerate newValue) {
        var index = TestComponentsLookup.ClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassToGenerateComponent)componentPool.Pop()
            : new ClassToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveClassToGenerate() {
        RemoveComponent(TestComponentsLookup.ClassToGenerate);

        return this;
    }


    public TestEntity SafeRemoveClassToGenerate() {
        if (hasClassToGenerate)
        {
            RemoveComponent(TestComponentsLookup.ClassToGenerate);
        }

        return this;
    }
}

public partial class TestEntity : IClassToGenerateEntity {
    void IClassToGenerateEntity.AddClassToGenerate(My.Namespace.ClassToGenerate newValue) { AddClassToGenerate(newValue); }
    void IClassToGenerateEntity.ReplaceClassToGenerate(My.Namespace.ClassToGenerate newValue) { ReplaceClassToGenerate(newValue); }
    void IClassToGenerateEntity.RemoveClassToGenerate() { RemoveClassToGenerate(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherClassToGenerate;

    public static Entitas.IMatcher<TestEntity> ClassToGenerate {
        get {
            if (_matcherClassToGenerate == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.ClassToGenerate);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherClassToGenerate = matcher;
            }

            return _matcherClassToGenerate;
        }
    }
}

