// <auto-generated/>
public sealed partial class TestContext : Entitas.Context<TestEntity> {

    public TestContext()
        : base(
            TestComponentsLookup.TotalComponents,
            0,
            new Entitas.ContextInfo(
                "Test",
                TestComponentsLookup.componentNames,
                TestComponentsLookup.componentTypes
            ),
            (entity) =>

#if (ENTITAS_FAST_AND_UNSAFE)
                new Entitas.UnsafeAERC(),
#else
                new Entitas.SafeAERC(entity),
#endif
            () => new TestEntity()
        ) {
    }
}

