// <auto-generated/>
public partial class TestContext {

    Entitas.IGroup<TestEntity> _myNamespaceUniqueMyNamespaceFlagGroup;

    public TestEntity myNamespaceUniqueMyNamespaceFlagEntity { get { return (_myNamespaceUniqueMyNamespaceFlagGroup ?? (_myNamespaceUniqueMyNamespaceFlagGroup = GetGroup(TestMatcher.MyNamespaceUniqueMyNamespaceFlag))).GetSingleEntity(); } }

    public bool isMyNamespaceUniqueMyNamespaceFlag {
        get { return myNamespaceUniqueMyNamespaceFlagEntity != null; }
        set {
            var entity = myNamespaceUniqueMyNamespaceFlagEntity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().isMyNamespaceUniqueMyNamespaceFlag = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}

public partial class TestEntity {

    static readonly My.Namespace.UniqueMyNamespaceFlagComponent myNamespaceUniqueMyNamespaceFlagComponent = new My.Namespace.UniqueMyNamespaceFlagComponent();

    public bool isMyNamespaceUniqueMyNamespaceFlag {
        get { return HasComponent(TestComponentsLookup.MyNamespaceUniqueMyNamespaceFlag); }
        set {
            if (value != isMyNamespaceUniqueMyNamespaceFlag) {
                var index = TestComponentsLookup.MyNamespaceUniqueMyNamespaceFlag;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : myNamespaceUniqueMyNamespaceFlagComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMyNamespaceUniqueMyNamespaceFlag;

    public static Entitas.IMatcher<TestEntity> MyNamespaceUniqueMyNamespaceFlag {
        get {
            if (_matcherMyNamespaceUniqueMyNamespaceFlag == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MyNamespaceUniqueMyNamespaceFlag);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMyNamespaceUniqueMyNamespaceFlag = matcher;
            }

            return _matcherMyNamespaceUniqueMyNamespaceFlag;
        }
    }
}

