// <auto-generated/>
public partial class TestEntity {

    public ComponentWithFieldsAndProperties componentWithFieldsAndProperties { get { return (ComponentWithFieldsAndProperties)GetComponent(TestComponentsLookup.ComponentWithFieldsAndProperties); } }
    public bool hasComponentWithFieldsAndProperties { get { return HasComponent(TestComponentsLookup.ComponentWithFieldsAndProperties); } }

    public TestEntity AddComponentWithFieldsAndProperties(string newPublicField, string newPublicProperty) {
        var index = TestComponentsLookup.ComponentWithFieldsAndProperties;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithFieldsAndProperties)componentPool.Pop()
            : new ComponentWithFieldsAndProperties();
        component.publicField = newPublicField;
        component.publicProperty = newPublicProperty;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceComponentWithFieldsAndProperties(string newPublicField, string newPublicProperty) {
        var index = TestComponentsLookup.ComponentWithFieldsAndProperties;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithFieldsAndProperties)componentPool.Pop()
            : new ComponentWithFieldsAndProperties();
        component.publicField = newPublicField;
        component.publicProperty = newPublicProperty;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveComponentWithFieldsAndProperties() {
        RemoveComponent(TestComponentsLookup.ComponentWithFieldsAndProperties);

        return this;
    }


    public TestEntity SafeRemoveComponentWithFieldsAndProperties() {
        if (hasComponentWithFieldsAndProperties)
        {
            RemoveComponent(TestComponentsLookup.ComponentWithFieldsAndProperties);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherComponentWithFieldsAndProperties;

    public static Entitas.IMatcher<TestEntity> ComponentWithFieldsAndProperties {
        get {
            if (_matcherComponentWithFieldsAndProperties == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.ComponentWithFieldsAndProperties);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherComponentWithFieldsAndProperties = matcher;
            }

            return _matcherComponentWithFieldsAndProperties;
        }
    }
}

