// <auto-generated/>
public partial class Test2Entity {

    public Test2AnyMultipleContextStandardEventListenerComponent test2AnyMultipleContextStandardEventListener { get { return (Test2AnyMultipleContextStandardEventListenerComponent)GetComponent(Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener); } }
    public bool hasTest2AnyMultipleContextStandardEventListener { get { return HasComponent(Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener); } }

    public Test2Entity AddTest2AnyMultipleContextStandardEventListener(System.Collections.Generic.List<ITest2AnyMultipleContextStandardEventListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyMultipleContextStandardEventListenerComponent)componentPool.Pop()
            : new Test2AnyMultipleContextStandardEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceTest2AnyMultipleContextStandardEventListener(System.Collections.Generic.List<ITest2AnyMultipleContextStandardEventListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyMultipleContextStandardEventListenerComponent)componentPool.Pop()
            : new Test2AnyMultipleContextStandardEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveTest2AnyMultipleContextStandardEventListener() {
        RemoveComponent(Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener);

        return this;
    }


    public Test2Entity SafeRemoveTest2AnyMultipleContextStandardEventListener() {
        if (hasTest2AnyMultipleContextStandardEventListener)
        {
            RemoveComponent(Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener);
        }

        return this;
    }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherTest2AnyMultipleContextStandardEventListener;

    public static Entitas.IMatcher<Test2Entity> Test2AnyMultipleContextStandardEventListener {
        get {
            if (_matcherTest2AnyMultipleContextStandardEventListener == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.Test2AnyMultipleContextStandardEventListener);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherTest2AnyMultipleContextStandardEventListener = matcher;
            }

            return _matcherTest2AnyMultipleContextStandardEventListener;
        }
    }
}

public partial class Test2Entity {

    public void AddTest2AnyMultipleContextStandardEventListener(ITest2AnyMultipleContextStandardEventListener value) {
        var listeners = hasTest2AnyMultipleContextStandardEventListener
            ? test2AnyMultipleContextStandardEventListener.value
            : new System.Collections.Generic.List<ITest2AnyMultipleContextStandardEventListener>();
        listeners.Add(value);
        ReplaceTest2AnyMultipleContextStandardEventListener(listeners);
    }

    public void RemoveTest2AnyMultipleContextStandardEventListener(ITest2AnyMultipleContextStandardEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = test2AnyMultipleContextStandardEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTest2AnyMultipleContextStandardEventListener();
        } else {
            ReplaceTest2AnyMultipleContextStandardEventListener(listeners);
        }
    }
}

