// <auto-generated/>
public partial class TestContext {

    Entitas.IGroup<TestEntity> _uniqueFlagGroup;

    public TestEntity uniqueFlagEntity { get { return (_uniqueFlagGroup ?? (_uniqueFlagGroup = GetGroup(TestMatcher.UniqueFlag))).GetSingleEntity(); } }

    public bool isUniqueFlag {
        get { return uniqueFlagEntity != null; }
        set {
            var entity = uniqueFlagEntity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().isUniqueFlag = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}

public partial class TestEntity {

    static readonly UniqueFlagComponent uniqueFlagComponent = new UniqueFlagComponent();

    public bool isUniqueFlag {
        get { return HasComponent(TestComponentsLookup.UniqueFlag); }
        set {
            if (value != isUniqueFlag) {
                var index = TestComponentsLookup.UniqueFlag;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : uniqueFlagComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherUniqueFlag;

    public static Entitas.IMatcher<TestEntity> UniqueFlag {
        get {
            if (_matcherUniqueFlag == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.UniqueFlag);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherUniqueFlag = matcher;
            }

            return _matcherUniqueFlag;
        }
    }
}

