// <auto-generated/>
public partial class TestEntity {

    public AnyUniqueEventListenerComponent anyUniqueEventListener { get { return (AnyUniqueEventListenerComponent)GetComponent(TestComponentsLookup.AnyUniqueEventListener); } }
    public bool hasAnyUniqueEventListener { get { return HasComponent(TestComponentsLookup.AnyUniqueEventListener); } }

    public TestEntity AddAnyUniqueEventListener(System.Collections.Generic.List<IAnyUniqueEventListener> newValue) {
        var index = TestComponentsLookup.AnyUniqueEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyUniqueEventListenerComponent)componentPool.Pop()
            : new AnyUniqueEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceAnyUniqueEventListener(System.Collections.Generic.List<IAnyUniqueEventListener> newValue) {
        var index = TestComponentsLookup.AnyUniqueEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyUniqueEventListenerComponent)componentPool.Pop()
            : new AnyUniqueEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveAnyUniqueEventListener() {
        RemoveComponent(TestComponentsLookup.AnyUniqueEventListener);

        return this;
    }


    public TestEntity SafeRemoveAnyUniqueEventListener() {
        if (hasAnyUniqueEventListener)
        {
            RemoveComponent(TestComponentsLookup.AnyUniqueEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherAnyUniqueEventListener;

    public static Entitas.IMatcher<TestEntity> AnyUniqueEventListener {
        get {
            if (_matcherAnyUniqueEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.AnyUniqueEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherAnyUniqueEventListener = matcher;
            }

            return _matcherAnyUniqueEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddAnyUniqueEventListener(IAnyUniqueEventListener value) {
        var listeners = hasAnyUniqueEventListener
            ? anyUniqueEventListener.value
            : new System.Collections.Generic.List<IAnyUniqueEventListener>();
        listeners.Add(value);
        ReplaceAnyUniqueEventListener(listeners);
    }

    public void RemoveAnyUniqueEventListener(IAnyUniqueEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = anyUniqueEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveAnyUniqueEventListener();
        } else {
            ReplaceAnyUniqueEventListener(listeners);
        }
    }
}

