// <auto-generated/>
public partial class TestEntity {

    public ClassWithEntitIndexAttributeComponent classWithEntitIndexAttribute { get { return (ClassWithEntitIndexAttributeComponent)GetComponent(TestComponentsLookup.ClassWithEntitIndexAttribute); } }
    public bool hasClassWithEntitIndexAttribute { get { return HasComponent(TestComponentsLookup.ClassWithEntitIndexAttribute); } }

    public TestEntity AddClassWithEntitIndexAttribute(ClassWithEntitIndexAttribute newValue) {
        var index = TestComponentsLookup.ClassWithEntitIndexAttribute;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassWithEntitIndexAttributeComponent)componentPool.Pop()
            : new ClassWithEntitIndexAttributeComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceClassWithEntitIndexAttribute(ClassWithEntitIndexAttribute newValue) {
        var index = TestComponentsLookup.ClassWithEntitIndexAttribute;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ClassWithEntitIndexAttributeComponent)componentPool.Pop()
            : new ClassWithEntitIndexAttributeComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveClassWithEntitIndexAttribute() {
        RemoveComponent(TestComponentsLookup.ClassWithEntitIndexAttribute);

        return this;
    }


    public TestEntity SafeRemoveClassWithEntitIndexAttribute() {
        if (hasClassWithEntitIndexAttribute)
        {
            RemoveComponent(TestComponentsLookup.ClassWithEntitIndexAttribute);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherClassWithEntitIndexAttribute;

    public static Entitas.IMatcher<TestEntity> ClassWithEntitIndexAttribute {
        get {
            if (_matcherClassWithEntitIndexAttribute == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.ClassWithEntitIndexAttribute);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherClassWithEntitIndexAttribute = matcher;
            }

            return _matcherClassWithEntitIndexAttribute;
        }
    }
}

