// <auto-generated/>
public partial class TestEntity {

    public InterfaceToGenerateComponent interfaceToGenerate { get { return (InterfaceToGenerateComponent)GetComponent(TestComponentsLookup.InterfaceToGenerate); } }
    public bool hasInterfaceToGenerate { get { return HasComponent(TestComponentsLookup.InterfaceToGenerate); } }

    public TestEntity AddInterfaceToGenerate(My.Namespace.InterfaceToGenerate newValue) {
        var index = TestComponentsLookup.InterfaceToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (InterfaceToGenerateComponent)componentPool.Pop()
            : new InterfaceToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceInterfaceToGenerate(My.Namespace.InterfaceToGenerate newValue) {
        var index = TestComponentsLookup.InterfaceToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (InterfaceToGenerateComponent)componentPool.Pop()
            : new InterfaceToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveInterfaceToGenerate() {
        RemoveComponent(TestComponentsLookup.InterfaceToGenerate);

        return this;
    }


    public TestEntity SafeRemoveInterfaceToGenerate() {
        if (hasInterfaceToGenerate)
        {
            RemoveComponent(TestComponentsLookup.InterfaceToGenerate);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherInterfaceToGenerate;

    public static Entitas.IMatcher<TestEntity> InterfaceToGenerate {
        get {
            if (_matcherInterfaceToGenerate == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.InterfaceToGenerate);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherInterfaceToGenerate = matcher;
            }

            return _matcherInterfaceToGenerate;
        }
    }
}

