// <auto-generated/>
public partial class Test2Entity {

    public Test2AnyEventToGenerateListenerComponent test2AnyEventToGenerateListener { get { return (Test2AnyEventToGenerateListenerComponent)GetComponent(Test2ComponentsLookup.Test2AnyEventToGenerateListener); } }
    public bool hasTest2AnyEventToGenerateListener { get { return HasComponent(Test2ComponentsLookup.Test2AnyEventToGenerateListener); } }

    public Test2Entity AddTest2AnyEventToGenerateListener(System.Collections.Generic.List<ITest2AnyEventToGenerateListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyEventToGenerateListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyEventToGenerateListenerComponent)componentPool.Pop()
            : new Test2AnyEventToGenerateListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceTest2AnyEventToGenerateListener(System.Collections.Generic.List<ITest2AnyEventToGenerateListener> newValue) {
        var index = Test2ComponentsLookup.Test2AnyEventToGenerateListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (Test2AnyEventToGenerateListenerComponent)componentPool.Pop()
            : new Test2AnyEventToGenerateListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveTest2AnyEventToGenerateListener() {
        RemoveComponent(Test2ComponentsLookup.Test2AnyEventToGenerateListener);

        return this;
    }


    public Test2Entity SafeRemoveTest2AnyEventToGenerateListener() {
        if (hasTest2AnyEventToGenerateListener)
        {
            RemoveComponent(Test2ComponentsLookup.Test2AnyEventToGenerateListener);
        }

        return this;
    }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherTest2AnyEventToGenerateListener;

    public static Entitas.IMatcher<Test2Entity> Test2AnyEventToGenerateListener {
        get {
            if (_matcherTest2AnyEventToGenerateListener == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.Test2AnyEventToGenerateListener);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherTest2AnyEventToGenerateListener = matcher;
            }

            return _matcherTest2AnyEventToGenerateListener;
        }
    }
}

public partial class Test2Entity {

    public void AddTest2AnyEventToGenerateListener(ITest2AnyEventToGenerateListener value) {
        var listeners = hasTest2AnyEventToGenerateListener
            ? test2AnyEventToGenerateListener.value
            : new System.Collections.Generic.List<ITest2AnyEventToGenerateListener>();
        listeners.Add(value);
        ReplaceTest2AnyEventToGenerateListener(listeners);
    }

    public void RemoveTest2AnyEventToGenerateListener(ITest2AnyEventToGenerateListener value, bool removeComponentWhenEmpty = true) {
        var listeners = test2AnyEventToGenerateListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTest2AnyEventToGenerateListener();
        } else {
            ReplaceTest2AnyEventToGenerateListener(listeners);
        }
    }
}

