// <auto-generated/>
public partial class TestEntity {

    public AnyStandardEventListenerComponent anyStandardEventListener { get { return (AnyStandardEventListenerComponent)GetComponent(TestComponentsLookup.AnyStandardEventListener); } }
    public bool hasAnyStandardEventListener { get { return HasComponent(TestComponentsLookup.AnyStandardEventListener); } }

    public TestEntity AddAnyStandardEventListener(System.Collections.Generic.List<IAnyStandardEventListener> newValue) {
        var index = TestComponentsLookup.AnyStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyStandardEventListenerComponent)componentPool.Pop()
            : new AnyStandardEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceAnyStandardEventListener(System.Collections.Generic.List<IAnyStandardEventListener> newValue) {
        var index = TestComponentsLookup.AnyStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyStandardEventListenerComponent)componentPool.Pop()
            : new AnyStandardEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveAnyStandardEventListener() {
        RemoveComponent(TestComponentsLookup.AnyStandardEventListener);

        return this;
    }


    public TestEntity SafeRemoveAnyStandardEventListener() {
        if (hasAnyStandardEventListener)
        {
            RemoveComponent(TestComponentsLookup.AnyStandardEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherAnyStandardEventListener;

    public static Entitas.IMatcher<TestEntity> AnyStandardEventListener {
        get {
            if (_matcherAnyStandardEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.AnyStandardEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherAnyStandardEventListener = matcher;
            }

            return _matcherAnyStandardEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddAnyStandardEventListener(IAnyStandardEventListener value) {
        var listeners = hasAnyStandardEventListener
            ? anyStandardEventListener.value
            : new System.Collections.Generic.List<IAnyStandardEventListener>();
        listeners.Add(value);
        ReplaceAnyStandardEventListener(listeners);
    }

    public void RemoveAnyStandardEventListener(IAnyStandardEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = anyStandardEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveAnyStandardEventListener();
        } else {
            ReplaceAnyStandardEventListener(listeners);
        }
    }
}

