// <auto-generated/>
public partial class TestEntity {

    public My.Namespace.EntityIndexComponent myNamespaceEntityIndex { get { return (My.Namespace.EntityIndexComponent)GetComponent(TestComponentsLookup.MyNamespaceEntityIndex); } }
    public bool hasMyNamespaceEntityIndex { get { return HasComponent(TestComponentsLookup.MyNamespaceEntityIndex); } }

    public TestEntity AddMyNamespaceEntityIndex(string newValue) {
        var index = TestComponentsLookup.MyNamespaceEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.EntityIndexComponent)componentPool.Pop()
            : new My.Namespace.EntityIndexComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMyNamespaceEntityIndex(string newValue) {
        var index = TestComponentsLookup.MyNamespaceEntityIndex;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.EntityIndexComponent)componentPool.Pop()
            : new My.Namespace.EntityIndexComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMyNamespaceEntityIndex() {
        RemoveComponent(TestComponentsLookup.MyNamespaceEntityIndex);

        return this;
    }


    public TestEntity SafeRemoveMyNamespaceEntityIndex() {
        if (hasMyNamespaceEntityIndex)
        {
            RemoveComponent(TestComponentsLookup.MyNamespaceEntityIndex);
        }

        return this;
    }
}

public partial class TestEntity : IMyNamespaceEntityIndexEntity {
    void IMyNamespaceEntityIndexEntity.AddMyNamespaceEntityIndex(string newValue) { AddMyNamespaceEntityIndex(newValue); }
    void IMyNamespaceEntityIndexEntity.ReplaceMyNamespaceEntityIndex(string newValue) { ReplaceMyNamespaceEntityIndex(newValue); }
    void IMyNamespaceEntityIndexEntity.RemoveMyNamespaceEntityIndex() { RemoveMyNamespaceEntityIndex(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMyNamespaceEntityIndex;

    public static Entitas.IMatcher<TestEntity> MyNamespaceEntityIndex {
        get {
            if (_matcherMyNamespaceEntityIndex == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MyNamespaceEntityIndex);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMyNamespaceEntityIndex = matcher;
            }

            return _matcherMyNamespaceEntityIndex;
        }
    }
}

