// <auto-generated/>
public partial class TestEntity {

    public StandardComponent standard { get { return (StandardComponent)GetComponent(TestComponentsLookup.Standard); } }
    public bool hasStandard { get { return HasComponent(TestComponentsLookup.Standard); } }

    public TestEntity AddStandard(string newValue) {
        var index = TestComponentsLookup.Standard;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardComponent)componentPool.Pop()
            : new StandardComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceStandard(string newValue) {
        var index = TestComponentsLookup.Standard;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (StandardComponent)componentPool.Pop()
            : new StandardComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveStandard() {
        RemoveComponent(TestComponentsLookup.Standard);

        return this;
    }


    public TestEntity SafeRemoveStandard() {
        if (hasStandard)
        {
            RemoveComponent(TestComponentsLookup.Standard);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherStandard;

    public static Entitas.IMatcher<TestEntity> Standard {
        get {
            if (_matcherStandard == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.Standard);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherStandard = matcher;
            }

            return _matcherStandard;
        }
    }
}

