// <auto-generated/>
public partial class TestEntity {

    static readonly FlagComponent flagComponent = new FlagComponent();

    public bool isFlag {
        get { return HasComponent(TestComponentsLookup.Flag); }
        set {
            if (value != isFlag) {
                var index = TestComponentsLookup.Flag;
                if (value) {
                    var componentPool = GetComponentPool(index);
                    var component = componentPool.Count > 0
                            ? componentPool.Pop()
                            : flagComponent;

                    AddComponent(index, component);
                } else {
                    RemoveComponent(index);
                }
            }
        }
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherFlag;

    public static Entitas.IMatcher<TestEntity> Flag {
        get {
            if (_matcherFlag == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.Flag);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherFlag = matcher;
            }

            return _matcherFlag;
        }
    }
}

