// <auto-generated/>
public sealed partial class TestMatcher {

    public static Entitas.IAllOfMatcher<TestEntity> AllOf(params int[] indices) {
        return Entitas.Matcher<TestEntity>.AllOf(indices);
    }

    public static Entitas.IAllOfMatcher<TestEntity> AllOf(params Entitas.IMatcher<TestEntity>[] matchers) {
          return Entitas.Matcher<TestEntity>.AllOf(matchers);
    }

    public static Entitas.IAnyOfMatcher<TestEntity> AnyOf(params int[] indices) {
          return Entitas.Matcher<TestEntity>.AnyOf(indices);
    }

    public static Entitas.IAnyOfMatcher<TestEntity> AnyOf(params Entitas.IMatcher<TestEntity>[] matchers) {
          return Entitas.Matcher<TestEntity>.AnyOf(matchers);
    }
}

