// <auto-generated/>
public partial class TestEntity {

    public SizeComponent size { get { return (SizeComponent)GetComponent(TestComponentsLookup.Size); } }
    public bool hasSize { get { return HasComponent(TestComponentsLookup.Size); } }

    public TestEntity AddSize(int newWidth, int newHeight) {
        var index = TestComponentsLookup.Size;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (SizeComponent)componentPool.Pop()
            : new SizeComponent();
        component.width = newWidth;
        component.height = newHeight;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceSize(int newWidth, int newHeight) {
        var index = TestComponentsLookup.Size;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (SizeComponent)componentPool.Pop()
            : new SizeComponent();
        component.width = newWidth;
        component.height = newHeight;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveSize() {
        RemoveComponent(TestComponentsLookup.Size);

        return this;
    }


    public TestEntity SafeRemoveSize() {
        if (hasSize)
        {
            RemoveComponent(TestComponentsLookup.Size);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherSize;

    public static Entitas.IMatcher<TestEntity> Size {
        get {
            if (_matcherSize == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.Size);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherSize = matcher;
            }

            return _matcherSize;
        }
    }
}

