// <auto-generated/>
public partial class Test2Entity {

    public MultipleContextStandardEventComponent multipleContextStandardEvent { get { return (MultipleContextStandardEventComponent)GetComponent(Test2ComponentsLookup.MultipleContextStandardEvent); } }
    public bool hasMultipleContextStandardEvent { get { return HasComponent(Test2ComponentsLookup.MultipleContextStandardEvent); } }

    public Test2Entity AddMultipleContextStandardEvent(string newValue) {
        var index = Test2ComponentsLookup.MultipleContextStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleContextStandardEventComponent)componentPool.Pop()
            : new MultipleContextStandardEventComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public Test2Entity ReplaceMultipleContextStandardEvent(string newValue) {
        var index = Test2ComponentsLookup.MultipleContextStandardEvent;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (MultipleContextStandardEventComponent)componentPool.Pop()
            : new MultipleContextStandardEventComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public Test2Entity RemoveMultipleContextStandardEvent() {
        RemoveComponent(Test2ComponentsLookup.MultipleContextStandardEvent);

        return this;
    }


    public Test2Entity SafeRemoveMultipleContextStandardEvent() {
        if (hasMultipleContextStandardEvent)
        {
            RemoveComponent(Test2ComponentsLookup.MultipleContextStandardEvent);
        }

        return this;
    }
}

public partial class Test2Entity : IMultipleContextStandardEventEntity {
    void IMultipleContextStandardEventEntity.AddMultipleContextStandardEvent(string newValue) { AddMultipleContextStandardEvent(newValue); }
    void IMultipleContextStandardEventEntity.ReplaceMultipleContextStandardEvent(string newValue) { ReplaceMultipleContextStandardEvent(newValue); }
    void IMultipleContextStandardEventEntity.RemoveMultipleContextStandardEvent() { RemoveMultipleContextStandardEvent(); }
}

public sealed partial class Test2Matcher {

    static Entitas.IMatcher<Test2Entity> _matcherMultipleContextStandardEvent;

    public static Entitas.IMatcher<Test2Entity> MultipleContextStandardEvent {
        get {
            if (_matcherMultipleContextStandardEvent == null) {
                var matcher = (Entitas.Matcher<Test2Entity>)Entitas.Matcher<Test2Entity>.AllOf(Test2ComponentsLookup.MultipleContextStandardEvent);
                matcher.componentNames = Test2ComponentsLookup.componentNames;
                _matcherMultipleContextStandardEvent = matcher;
            }

            return _matcherMultipleContextStandardEvent;
        }
    }
}

