// <auto-generated/>
public partial class TestEntity {

    public TestAnyMultipleEventsStandardEventListenerComponent testAnyMultipleEventsStandardEventListener { get { return (TestAnyMultipleEventsStandardEventListenerComponent)GetComponent(TestComponentsLookup.TestAnyMultipleEventsStandardEventListener); } }
    public bool hasTestAnyMultipleEventsStandardEventListener { get { return HasComponent(TestComponentsLookup.TestAnyMultipleEventsStandardEventListener); } }

    public TestEntity AddTestAnyMultipleEventsStandardEventListener(System.Collections.Generic.List<ITestAnyMultipleEventsStandardEventListener> newValue) {
        var index = TestComponentsLookup.TestAnyMultipleEventsStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestAnyMultipleEventsStandardEventListenerComponent)componentPool.Pop()
            : new TestAnyMultipleEventsStandardEventListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceTestAnyMultipleEventsStandardEventListener(System.Collections.Generic.List<ITestAnyMultipleEventsStandardEventListener> newValue) {
        var index = TestComponentsLookup.TestAnyMultipleEventsStandardEventListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestAnyMultipleEventsStandardEventListenerComponent)componentPool.Pop()
            : new TestAnyMultipleEventsStandardEventListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveTestAnyMultipleEventsStandardEventListener() {
        RemoveComponent(TestComponentsLookup.TestAnyMultipleEventsStandardEventListener);

        return this;
    }


    public TestEntity SafeRemoveTestAnyMultipleEventsStandardEventListener() {
        if (hasTestAnyMultipleEventsStandardEventListener)
        {
            RemoveComponent(TestComponentsLookup.TestAnyMultipleEventsStandardEventListener);
        }

        return this;
    }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherTestAnyMultipleEventsStandardEventListener;

    public static Entitas.IMatcher<TestEntity> TestAnyMultipleEventsStandardEventListener {
        get {
            if (_matcherTestAnyMultipleEventsStandardEventListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.TestAnyMultipleEventsStandardEventListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherTestAnyMultipleEventsStandardEventListener = matcher;
            }

            return _matcherTestAnyMultipleEventsStandardEventListener;
        }
    }
}

public partial class TestEntity {

    public void AddTestAnyMultipleEventsStandardEventListener(ITestAnyMultipleEventsStandardEventListener value) {
        var listeners = hasTestAnyMultipleEventsStandardEventListener
            ? testAnyMultipleEventsStandardEventListener.value
            : new System.Collections.Generic.List<ITestAnyMultipleEventsStandardEventListener>();
        listeners.Add(value);
        ReplaceTestAnyMultipleEventsStandardEventListener(listeners);
    }

    public void RemoveTestAnyMultipleEventsStandardEventListener(ITestAnyMultipleEventsStandardEventListener value, bool removeComponentWhenEmpty = true) {
        var listeners = testAnyMultipleEventsStandardEventListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTestAnyMultipleEventsStandardEventListener();
        } else {
            ReplaceTestAnyMultipleEventsStandardEventListener(listeners);
        }
    }
}

