// <auto-generated/>
public partial class TestEntity {

    public EventToGenerateComponent eventToGenerate { get { return (EventToGenerateComponent)GetComponent(TestComponentsLookup.EventToGenerate); } }
    public bool hasEventToGenerate { get { return HasComponent(TestComponentsLookup.EventToGenerate); } }

    public TestEntity AddEventToGenerate(My.Namespace.EventToGenerate newValue) {
        var index = TestComponentsLookup.EventToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventToGenerateComponent)componentPool.Pop()
            : new EventToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceEventToGenerate(My.Namespace.EventToGenerate newValue) {
        var index = TestComponentsLookup.EventToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (EventToGenerateComponent)componentPool.Pop()
            : new EventToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveEventToGenerate() {
        RemoveComponent(TestComponentsLookup.EventToGenerate);

        return this;
    }


    public TestEntity SafeRemoveEventToGenerate() {
        if (hasEventToGenerate)
        {
            RemoveComponent(TestComponentsLookup.EventToGenerate);
        }

        return this;
    }
}

public partial class TestEntity : IEventToGenerateEntity {
    void IEventToGenerateEntity.AddEventToGenerate(My.Namespace.EventToGenerate newValue) { AddEventToGenerate(newValue); }
    void IEventToGenerateEntity.ReplaceEventToGenerate(My.Namespace.EventToGenerate newValue) { ReplaceEventToGenerate(newValue); }
    void IEventToGenerateEntity.RemoveEventToGenerate() { RemoveEventToGenerate(); }
}

public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherEventToGenerate;

    public static Entitas.IMatcher<TestEntity> EventToGenerate {
        get {
            if (_matcherEventToGenerate == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.EventToGenerate);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherEventToGenerate = matcher;
            }

            return _matcherEventToGenerate;
        }
    }
}

