//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentLookupGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public static class TestComponentsLookup {

    public const int AnyFlagEventRemovedListener = 0;
    public const int AnyMixedEventListener = 1;
    public const int AnyStandardEventListener = 2;
    public const int AnyUniqueEventListener = 3;
    public const int ClassToGenerate = 4;
    public const int ClassWithEntitIndexAttribute = 5;
    public const int ComponentWithFields = 6;
    public const int ComponentWithFieldsAndProperties = 7;
    public const int ComponentWithProperties = 8;
    public const int CustomPrefixFlag = 9;
    public const int EventToGenerate = 10;
    public const int Flag = 11;
    public const int FlagEntityEvent = 12;
    public const int FlagEntityEventListener = 13;
    public const int FlagEvent = 14;
    public const int InterfaceToGenerate = 15;
    public const int MixedEvent = 16;
    public const int MixedEventListener = 17;
    public const int MultipleContextStandardEvent = 18;
    public const int MultipleEventsStandardEvent = 19;
    public const int MyNamespaceEntityIndex = 20;
    public const int MyNamespaceMultipleEntityIndices = 21;
    public const int MyNamespaceMyNamespace = 22;
    public const int MyNamespaceMyNamespaceFlag = 23;
    public const int MyNamespaceUniqueMyNamespace = 24;
    public const int MyNamespaceUniqueMyNamespaceFlag = 25;
    public const int NameAge = 26;
    public const int NewCustomNameComponent1 = 27;
    public const int NewCustomNameComponent2 = 28;
    public const int Position = 29;
    public const int Size = 30;
    public const int Standard = 31;
    public const int StandardEntityEvent = 32;
    public const int StandardEntityEventRemovedListener = 33;
    public const int StandardEvent = 34;
    public const int StructToGenerate = 35;
    public const int Test2Context = 36;
    public const int TestAnyEventToGenerateListener = 37;
    public const int TestAnyMultipleContextStandardEventListener = 38;
    public const int TestAnyMultipleEventsStandardEventListener = 39;
    public const int TestMultipleEventsStandardEventRemovedListener = 40;
    public const int UniqueClassToGenerate = 41;
    public const int UniqueEvent = 42;
    public const int UniqueFlag = 43;
    public const int UniqueStandard = 44;

    public const int TotalComponents = 45;

    public static readonly string[] componentNames = {
        "AnyFlagEventRemovedListener",
        "AnyMixedEventListener",
        "AnyStandardEventListener",
        "AnyUniqueEventListener",
        "ClassToGenerate",
        "ClassWithEntitIndexAttribute",
        "ComponentWithFields",
        "ComponentWithFieldsAndProperties",
        "ComponentWithProperties",
        "CustomPrefixFlag",
        "EventToGenerate",
        "Flag",
        "FlagEntityEvent",
        "FlagEntityEventListener",
        "FlagEvent",
        "InterfaceToGenerate",
        "MixedEvent",
        "MixedEventListener",
        "MultipleContextStandardEvent",
        "MultipleEventsStandardEvent",
        "MyNamespaceEntityIndex",
        "MyNamespaceMultipleEntityIndices",
        "MyNamespaceMyNamespace",
        "MyNamespaceMyNamespaceFlag",
        "MyNamespaceUniqueMyNamespace",
        "MyNamespaceUniqueMyNamespaceFlag",
        "NameAge",
        "NewCustomNameComponent1",
        "NewCustomNameComponent2",
        "Position",
        "Size",
        "Standard",
        "StandardEntityEvent",
        "StandardEntityEventRemovedListener",
        "StandardEvent",
        "StructToGenerate",
        "Test2Context",
        "TestAnyEventToGenerateListener",
        "TestAnyMultipleContextStandardEventListener",
        "TestAnyMultipleEventsStandardEventListener",
        "TestMultipleEventsStandardEventRemovedListener",
        "UniqueClassToGenerate",
        "UniqueEvent",
        "UniqueFlag",
        "UniqueStandard"
    };

    public static readonly System.Type[] componentTypes = {
        typeof(AnyFlagEventRemovedListenerComponent),
        typeof(AnyMixedEventListenerComponent),
        typeof(AnyStandardEventListenerComponent),
        typeof(AnyUniqueEventListenerComponent),
        typeof(ClassToGenerateComponent),
        typeof(ClassWithEntitIndexAttributeComponent),
        typeof(ComponentWithFields),
        typeof(ComponentWithFieldsAndProperties),
        typeof(ComponentWithProperties),
        typeof(CustomPrefixFlagComponent),
        typeof(EventToGenerateComponent),
        typeof(FlagComponent),
        typeof(FlagEntityEventComponent),
        typeof(FlagEntityEventListenerComponent),
        typeof(FlagEventComponent),
        typeof(InterfaceToGenerateComponent),
        typeof(MixedEventComponent),
        typeof(MixedEventListenerComponent),
        typeof(MultipleContextStandardEventComponent),
        typeof(MultipleEventsStandardEventComponent),
        typeof(My.Namespace.EntityIndexComponent),
        typeof(My.Namespace.MultipleEntityIndicesComponent),
        typeof(My.Namespace.MyNamespaceComponent),
        typeof(My.Namespace.MyNamespaceFlagComponent),
        typeof(My.Namespace.UniqueMyNamespaceComponent),
        typeof(My.Namespace.UniqueMyNamespaceFlagComponent),
        typeof(NameAgeComponent),
        typeof(NewCustomNameComponent1Component),
        typeof(NewCustomNameComponent2Component),
        typeof(PositionComponent),
        typeof(SizeComponent),
        typeof(StandardComponent),
        typeof(StandardEntityEventComponent),
        typeof(StandardEntityEventRemovedListenerComponent),
        typeof(StandardEventComponent),
        typeof(StructToGenerateComponent),
        typeof(Test2ContextComponent),
        typeof(TestAnyEventToGenerateListenerComponent),
        typeof(TestAnyMultipleContextStandardEventListenerComponent),
        typeof(TestAnyMultipleEventsStandardEventListenerComponent),
        typeof(TestMultipleEventsStandardEventRemovedListenerComponent),
        typeof(UniqueClassToGenerateComponent),
        typeof(UniqueEventComponent),
        typeof(UniqueFlagComponent),
        typeof(UniqueStandardComponent)
    };
}
