using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using FluentAssertions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;
using Xunit.Abstractions;

namespace Entitas.SourceGenerator.Tests
{
    /// <summary>
    /// Phase 4 golden equivalence: runs the real EntitasIncrementalGenerator over the
    /// actual TestFixtures component set and proves its output (as a normalized line
    /// multiset over ALL generated files combined) matches the FRESH Jenny baseline
    /// generated from the same inputs.
    ///
    /// The two pipelines partition declarations into files differently (Jenny MERGES
    /// fragments; the SG emits each fragment as its own partial-class source), so we
    /// compare at the level of normalized line multisets, not file-by-file.
    /// </summary>
    public class GoldenEquivalenceTests
    {
        readonly ITestOutputHelper _output;

        public GoldenEquivalenceTests(ITestOutputHelper output) => _output = output;

        const string AssemblyAttributes =
            "[assembly: Entitas.CodeGeneration.Attributes.ContextDefinition(\"Game\")]\n" +
            "[assembly: Entitas.CodeGeneration.Attributes.ContextDefinition(\"Test\")]\n" +
            "[assembly: Entitas.CodeGeneration.Attributes.ContextDefinition(\"Test2\")]\n";

        // Frozen Jenny baseline (ground truth) committed as a test fixture — produced
        // by the current Jenny generators from the TestFixtures project. Lives in the
        // repo so the equivalence test is reproducible across machines/CI (the original
        // generation requires building + running the Jenny CLI, which is removed in
        // Phase 6; this snapshot proves SG == Jenny-at-migration-time permanently).
        static string JennyBaselineDir => Path.Combine(
            RepoRoot(), "src", "Entitas.SourceGenerator", "tests", "JennyBaseline");

        static IEnumerable<MetadataReference> References()
        {
            var tpa = (string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!;
            foreach (var path in tpa.Split(Path.PathSeparator))
            {
                if (!string.IsNullOrEmpty(path) && File.Exists(path))
                    yield return MetadataReference.CreateFromFile(path);
            }

            yield return MetadataReference.CreateFromFile(typeof(Entitas.IComponent).Assembly.Location);
            yield return MetadataReference.CreateFromFile(
                typeof(Entitas.CodeGeneration.Attributes.ContextAttribute).Assembly.Location);
        }

        static string RepoRoot()
        {
            // Walk up from the test bin dir until we find the Fixtures folder.
            var dir = new DirectoryInfo(AppContext.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, "Tests", "TestFixtures", "Fixtures");
                if (Directory.Exists(candidate))
                    return dir.FullName;
                dir = dir.Parent;
            }
            // Fallback: hardcoded absolute repo path.
            const string hard = "/Volumes/SSD_250_GB/ProjectsSSD/Entitas-Flux/src/Entitas-Flux";
            if (Directory.Exists(Path.Combine(hard, "Tests", "TestFixtures", "Fixtures")))
                return hard;
            throw new DirectoryNotFoundException("Could not locate TestFixtures/Fixtures from " + AppContext.BaseDirectory);
        }

        static IReadOnlyList<SyntaxTree> InputTrees()
        {
            var fixturesDir = Path.Combine(RepoRoot(), "Tests", "TestFixtures", "Fixtures");
            var trees = new List<SyntaxTree>();
            foreach (var file in Directory.EnumerateFiles(fixturesDir, "*.cs", SearchOption.AllDirectories)
                         .OrderBy(p => p, StringComparer.Ordinal))
            {
                trees.Add(CSharpSyntaxTree.ParseText(File.ReadAllText(file), path: file));
            }
            trees.Add(CSharpSyntaxTree.ParseText(AssemblyAttributes));
            return trees;
        }

        static IReadOnlyList<string> RunSourceGenerator()
        {
            var compilation = CSharpCompilation.Create(
                "TestFixturesAsm",
                InputTrees(),
                References(),
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            var driver = CSharpGeneratorDriver.Create(new EntitasIncrementalGenerator());
            var result = driver.RunGenerators(compilation).GetRunResult();
            return result.GeneratedTrees.Select(t => t.ToString()).ToList();
        }

        // Normalize a source text into its set of significant lines:
        //  - strip the auto-generated header banner (//---...<auto-generated>...---)
        //  - strip a bare "// <auto-generated/>" line
        //  - drop empty/whitespace-only lines
        //  - trim trailing whitespace
        static IEnumerable<string> NormalizedLines(string source)
        {
            var lines = source.Replace("\r\n", "\n").Split('\n');
            foreach (var raw in lines)
            {
                var line = raw.TrimEnd();
                if (line.Length == 0)
                    continue;

                var trimmed = line.TrimStart();

                // Bare auto-generated marker.
                if (trimmed == "// <auto-generated/>")
                    continue;

                // Jenny header banner block lines all consist of "//" followed by
                // dashes / the <auto-generated> tag / explanatory text. The banner is:
                //   //------------------------------------------------------------------------------
                //   // <auto-generated>
                //   //     This code was generated by Jenny.
                //   ...
                //   // </auto-generated>
                //   //------------------------------------------------------------------------------
                if (IsBannerLine(trimmed))
                    continue;

                yield return line;
            }
        }

        static bool IsBannerLine(string trimmed)
        {
            if (!trimmed.StartsWith("//"))
                return false;
            var rest = trimmed.Substring(2).Trim();
            if (rest.Length == 0)
                return true; // bare "//" banner spacer
            if (rest.All(c => c == '-'))
                return true; // dashed rule
            if (rest == "<auto-generated>" || rest == "</auto-generated>")
                return true;
            if (rest.StartsWith("This code was generated by"))
                return true;
            if (rest.StartsWith("Changes to this file may cause"))
                return true;
            if (rest.StartsWith("the code is regenerated"))
                return true;
            return false;
        }

        static Dictionary<string, int> Multiset(IEnumerable<string> lines)
        {
            var m = new Dictionary<string, int>();
            foreach (var line in lines)
            {
                m.TryGetValue(line, out var c);
                m[line] = c + 1;
            }
            return m;
        }

        // Returns (onlyInA, onlyInB) as ordered lists of "count x line".
        static (List<string> onlyInA, List<string> onlyInB) Diff(
            Dictionary<string, int> a, Dictionary<string, int> b)
        {
            var onlyInA = new List<string>();
            var onlyInB = new List<string>();
            foreach (var kv in a)
            {
                b.TryGetValue(kv.Key, out var bc);
                var delta = kv.Value - bc;
                if (delta > 0)
                    onlyInA.Add($"{delta}x  {kv.Key}");
            }
            foreach (var kv in b)
            {
                a.TryGetValue(kv.Key, out var ac);
                var delta = kv.Value - ac;
                if (delta > 0)
                    onlyInB.Add($"{delta}x  {kv.Key}");
            }
            onlyInA.Sort(StringComparer.Ordinal);
            onlyInB.Sort(StringComparer.Ordinal);
            return (onlyInA, onlyInB);
        }

        [Fact]
        public void SourceGeneratorOutputMatchesJennyBaseline()
        {
            Directory.Exists(JennyBaselineDir).Should().BeTrue(
                $"the fresh Jenny baseline must exist at {JennyBaselineDir}");

            var jennyLines = Directory
                .EnumerateFiles(JennyBaselineDir, "*.cs", SearchOption.AllDirectories)
                .SelectMany(f => NormalizedLines(File.ReadAllText(f)));
            var jennyMultiset = Multiset(jennyLines);

            var sgSources = RunSourceGenerator();
            var sgMultiset = Multiset(sgSources.SelectMany(NormalizedLines));

            // Guard against a degenerate "both empty" pass (e.g. a generator throwing
            // and silently producing nothing): both pipelines must emit real volume.
            jennyMultiset.Values.Sum().Should().BeGreaterThan(500,
                "the Jenny baseline must contain real generated code");
            sgMultiset.Values.Sum().Should().BeGreaterThan(500,
                "the source generator must emit real generated code");

            var (onlyInJenny, onlyInSg) = Diff(jennyMultiset, sgMultiset);

            if (onlyInJenny.Count > 0 || onlyInSg.Count > 0)
            {
                var sb = new StringBuilder();
                sb.AppendLine($"=== Lines only in JENNY ({onlyInJenny.Count}) ===");
                foreach (var l in onlyInJenny) sb.AppendLine(l);
                sb.AppendLine();
                sb.AppendLine($"=== Lines only in SG ({onlyInSg.Count}) ===");
                foreach (var l in onlyInSg) sb.AppendLine(l);
                _output.WriteLine(sb.ToString());
            }

            onlyInJenny.Should().BeEmpty("every Jenny line must be reproduced by the SG");
            onlyInSg.Should().BeEmpty("the SG must not emit lines absent from Jenny");
        }
    }
}
