//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestContext {

    Entitas.IGroup<TestEntity> _uniqueStandardGroup;

    public TestEntity uniqueStandardEntity { get { return (_uniqueStandardGroup ?? (_uniqueStandardGroup = GetGroup(TestMatcher.UniqueStandard))).GetSingleEntity(); } }
    public UniqueStandardComponent uniqueStandard { get { return uniqueStandardEntity.uniqueStandard; } }
    public bool hasUniqueStandard { get { return uniqueStandardEntity != null; } }

    public TestEntity SetUniqueStandard(string newValue) {
        if (hasUniqueStandard) {
            throw new Entitas.EntitasException("Could not set UniqueStandard!\n" + this + " already has an entity with UniqueStandardComponent!",
                "You should check if the context already has a uniqueStandardEntity before setting it or use context.ReplaceUniqueStandard().");
        }
        var entity = CreateEntity();
        entity.AddUniqueStandard(newValue);
        return entity;
    }

    public void ReplaceUniqueStandard(string newValue) {
        var entity = uniqueStandardEntity;
        if (entity == null) {
            entity = SetUniqueStandard(newValue);
        } else {
            entity.ReplaceUniqueStandard(newValue);
        }
    }

    public void RemoveUniqueStandard() {
        uniqueStandardEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public UniqueStandardComponent uniqueStandard { get { return (UniqueStandardComponent)GetComponent(TestComponentsLookup.UniqueStandard); } }
    public bool hasUniqueStandard { get { return HasComponent(TestComponentsLookup.UniqueStandard); } }

    public TestEntity AddUniqueStandard(string newValue) {
        var index = TestComponentsLookup.UniqueStandard;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (UniqueStandardComponent)componentPool.Pop()
            : new UniqueStandardComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceUniqueStandard(string newValue) {
        var index = TestComponentsLookup.UniqueStandard;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (UniqueStandardComponent)componentPool.Pop()
            : new UniqueStandardComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveUniqueStandard() {
        RemoveComponent(TestComponentsLookup.UniqueStandard);

        return this;
    }


    public TestEntity SafeRemoveUniqueStandard() {
        if (hasUniqueStandard) 
        {
            RemoveComponent(TestComponentsLookup.UniqueStandard);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherUniqueStandard;

    public static Entitas.IMatcher<TestEntity> UniqueStandard {
        get {
            if (_matcherUniqueStandard == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.UniqueStandard);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherUniqueStandard = matcher;
            }

            return _matcherUniqueStandard;
        }
    }
}
