//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public AnyFlagEventRemovedListenerComponent anyFlagEventRemovedListener { get { return (AnyFlagEventRemovedListenerComponent)GetComponent(TestComponentsLookup.AnyFlagEventRemovedListener); } }
    public bool hasAnyFlagEventRemovedListener { get { return HasComponent(TestComponentsLookup.AnyFlagEventRemovedListener); } }

    public TestEntity AddAnyFlagEventRemovedListener(System.Collections.Generic.List<IAnyFlagEventRemovedListener> newValue) {
        var index = TestComponentsLookup.AnyFlagEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyFlagEventRemovedListenerComponent)componentPool.Pop()
            : new AnyFlagEventRemovedListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceAnyFlagEventRemovedListener(System.Collections.Generic.List<IAnyFlagEventRemovedListener> newValue) {
        var index = TestComponentsLookup.AnyFlagEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (AnyFlagEventRemovedListenerComponent)componentPool.Pop()
            : new AnyFlagEventRemovedListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveAnyFlagEventRemovedListener() {
        RemoveComponent(TestComponentsLookup.AnyFlagEventRemovedListener);

        return this;
    }


    public TestEntity SafeRemoveAnyFlagEventRemovedListener() {
        if (hasAnyFlagEventRemovedListener) 
        {
            RemoveComponent(TestComponentsLookup.AnyFlagEventRemovedListener);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherAnyFlagEventRemovedListener;

    public static Entitas.IMatcher<TestEntity> AnyFlagEventRemovedListener {
        get {
            if (_matcherAnyFlagEventRemovedListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.AnyFlagEventRemovedListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherAnyFlagEventRemovedListener = matcher;
            }

            return _matcherAnyFlagEventRemovedListener;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.EventEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public void AddAnyFlagEventRemovedListener(IAnyFlagEventRemovedListener value) {
        var listeners = hasAnyFlagEventRemovedListener
            ? anyFlagEventRemovedListener.value
            : new System.Collections.Generic.List<IAnyFlagEventRemovedListener>();
        listeners.Add(value);
        ReplaceAnyFlagEventRemovedListener(listeners);
    }

    public void RemoveAnyFlagEventRemovedListener(IAnyFlagEventRemovedListener value, bool removeComponentWhenEmpty = true) {
        var listeners = anyFlagEventRemovedListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveAnyFlagEventRemovedListener();
        } else {
            ReplaceAnyFlagEventRemovedListener(listeners);
        }
    }
}
