//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentContextApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestContext {

    Entitas.IGroup<TestEntity> _uniqueClassToGenerateGroup;

    public TestEntity uniqueClassToGenerateEntity { get { return (_uniqueClassToGenerateGroup ?? (_uniqueClassToGenerateGroup = GetGroup(TestMatcher.UniqueClassToGenerate))).GetSingleEntity(); } }
    public UniqueClassToGenerateComponent uniqueClassToGenerate { get { return uniqueClassToGenerateEntity.uniqueClassToGenerate; } }
    public bool hasUniqueClassToGenerate { get { return uniqueClassToGenerateEntity != null; } }

    public TestEntity SetUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) {
        if (hasUniqueClassToGenerate) {
            throw new Entitas.EntitasException("Could not set UniqueClassToGenerate!\n" + this + " already has an entity with UniqueClassToGenerateComponent!",
                "You should check if the context already has a uniqueClassToGenerateEntity before setting it or use context.ReplaceUniqueClassToGenerate().");
        }
        var entity = CreateEntity();
        entity.AddUniqueClassToGenerate(newValue);
        return entity;
    }

    public void ReplaceUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) {
        var entity = uniqueClassToGenerateEntity;
        if (entity == null) {
            entity = SetUniqueClassToGenerate(newValue);
        } else {
            entity.ReplaceUniqueClassToGenerate(newValue);
        }
    }

    public void RemoveUniqueClassToGenerate() {
        uniqueClassToGenerateEntity.Destroy();
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public UniqueClassToGenerateComponent uniqueClassToGenerate { get { return (UniqueClassToGenerateComponent)GetComponent(TestComponentsLookup.UniqueClassToGenerate); } }
    public bool hasUniqueClassToGenerate { get { return HasComponent(TestComponentsLookup.UniqueClassToGenerate); } }

    public TestEntity AddUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) {
        var index = TestComponentsLookup.UniqueClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (UniqueClassToGenerateComponent)componentPool.Pop()
            : new UniqueClassToGenerateComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) {
        var index = TestComponentsLookup.UniqueClassToGenerate;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (UniqueClassToGenerateComponent)componentPool.Pop()
            : new UniqueClassToGenerateComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveUniqueClassToGenerate() {
        RemoveComponent(TestComponentsLookup.UniqueClassToGenerate);

        return this;
    }


    public TestEntity SafeRemoveUniqueClassToGenerate() {
        if (hasUniqueClassToGenerate) 
        {
            RemoveComponent(TestComponentsLookup.UniqueClassToGenerate);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity : IUniqueClassToGenerateEntity {
    void IUniqueClassToGenerateEntity.AddUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) { AddUniqueClassToGenerate(newValue); }
    void IUniqueClassToGenerateEntity.ReplaceUniqueClassToGenerate(My.Namespace.UniqueClassToGenerate newValue) { ReplaceUniqueClassToGenerate(newValue); }
    void IUniqueClassToGenerateEntity.RemoveUniqueClassToGenerate() { RemoveUniqueClassToGenerate(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherUniqueClassToGenerate;

    public static Entitas.IMatcher<TestEntity> UniqueClassToGenerate {
        get {
            if (_matcherUniqueClassToGenerate == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.UniqueClassToGenerate);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherUniqueClassToGenerate = matcher;
            }

            return _matcherUniqueClassToGenerate;
        }
    }
}
