//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public PositionComponent position { get { return (PositionComponent)GetComponent(TestComponentsLookup.Position); } }
    public bool hasPosition { get { return HasComponent(TestComponentsLookup.Position); } }

    public TestEntity AddPosition(int newX, int newY) {
        var index = TestComponentsLookup.Position;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (PositionComponent)componentPool.Pop()
            : new PositionComponent();
        component.x = newX;
        component.y = newY;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplacePosition(int newX, int newY) {
        var index = TestComponentsLookup.Position;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (PositionComponent)componentPool.Pop()
            : new PositionComponent();
        component.x = newX;
        component.y = newY;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemovePosition() {
        RemoveComponent(TestComponentsLookup.Position);

        return this;
    }


    public TestEntity SafeRemovePosition() {
        if (hasPosition) 
        {
            RemoveComponent(TestComponentsLookup.Position);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherPosition;

    public static Entitas.IMatcher<TestEntity> Position {
        get {
            if (_matcherPosition == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.Position);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherPosition = matcher;
            }

            return _matcherPosition;
        }
    }
}
