//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public My.Namespace.MultipleEntityIndicesComponent myNamespaceMultipleEntityIndices { get { return (My.Namespace.MultipleEntityIndicesComponent)GetComponent(TestComponentsLookup.MyNamespaceMultipleEntityIndices); } }
    public bool hasMyNamespaceMultipleEntityIndices { get { return HasComponent(TestComponentsLookup.MyNamespaceMultipleEntityIndices); } }

    public TestEntity AddMyNamespaceMultipleEntityIndices(string newValue, string newValue2) {
        var index = TestComponentsLookup.MyNamespaceMultipleEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MultipleEntityIndicesComponent)componentPool.Pop()
            : new My.Namespace.MultipleEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMyNamespaceMultipleEntityIndices(string newValue, string newValue2) {
        var index = TestComponentsLookup.MyNamespaceMultipleEntityIndices;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MultipleEntityIndicesComponent)componentPool.Pop()
            : new My.Namespace.MultipleEntityIndicesComponent();
        component.value = newValue;
        component.value2 = newValue2;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMyNamespaceMultipleEntityIndices() {
        RemoveComponent(TestComponentsLookup.MyNamespaceMultipleEntityIndices);

        return this;
    }


    public TestEntity SafeRemoveMyNamespaceMultipleEntityIndices() {
        if (hasMyNamespaceMultipleEntityIndices) 
        {
            RemoveComponent(TestComponentsLookup.MyNamespaceMultipleEntityIndices);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity : IMyNamespaceMultipleEntityIndicesEntity {
    void IMyNamespaceMultipleEntityIndicesEntity.AddMyNamespaceMultipleEntityIndices(string newValue, string newValue2) { AddMyNamespaceMultipleEntityIndices(newValue, newValue2); }
    void IMyNamespaceMultipleEntityIndicesEntity.ReplaceMyNamespaceMultipleEntityIndices(string newValue, string newValue2) { ReplaceMyNamespaceMultipleEntityIndices(newValue, newValue2); }
    void IMyNamespaceMultipleEntityIndicesEntity.RemoveMyNamespaceMultipleEntityIndices() { RemoveMyNamespaceMultipleEntityIndices(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMyNamespaceMultipleEntityIndices;

    public static Entitas.IMatcher<TestEntity> MyNamespaceMultipleEntityIndices {
        get {
            if (_matcherMyNamespaceMultipleEntityIndices == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MyNamespaceMultipleEntityIndices);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMyNamespaceMultipleEntityIndices = matcher;
            }

            return _matcherMyNamespaceMultipleEntityIndices;
        }
    }
}
