//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public NewCustomNameComponent2Component newCustomNameComponent2 { get { return (NewCustomNameComponent2Component)GetComponent(TestComponentsLookup.NewCustomNameComponent2); } }
    public bool hasNewCustomNameComponent2 { get { return HasComponent(TestComponentsLookup.NewCustomNameComponent2); } }

    public TestEntity AddNewCustomNameComponent2(CustomName newValue) {
        var index = TestComponentsLookup.NewCustomNameComponent2;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NewCustomNameComponent2Component)componentPool.Pop()
            : new NewCustomNameComponent2Component();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceNewCustomNameComponent2(CustomName newValue) {
        var index = TestComponentsLookup.NewCustomNameComponent2;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (NewCustomNameComponent2Component)componentPool.Pop()
            : new NewCustomNameComponent2Component();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveNewCustomNameComponent2() {
        RemoveComponent(TestComponentsLookup.NewCustomNameComponent2);

        return this;
    }


    public TestEntity SafeRemoveNewCustomNameComponent2() {
        if (hasNewCustomNameComponent2) 
        {
            RemoveComponent(TestComponentsLookup.NewCustomNameComponent2);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherNewCustomNameComponent2;

    public static Entitas.IMatcher<TestEntity> NewCustomNameComponent2 {
        get {
            if (_matcherNewCustomNameComponent2 == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.NewCustomNameComponent2);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherNewCustomNameComponent2 = matcher;
            }

            return _matcherNewCustomNameComponent2;
        }
    }
}
