//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public ComponentWithFields componentWithFields { get { return (ComponentWithFields)GetComponent(TestComponentsLookup.ComponentWithFields); } }
    public bool hasComponentWithFields { get { return HasComponent(TestComponentsLookup.ComponentWithFields); } }

    public TestEntity AddComponentWithFields(string newPublicField) {
        var index = TestComponentsLookup.ComponentWithFields;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithFields)componentPool.Pop()
            : new ComponentWithFields();
        component.publicField = newPublicField;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceComponentWithFields(string newPublicField) {
        var index = TestComponentsLookup.ComponentWithFields;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (ComponentWithFields)componentPool.Pop()
            : new ComponentWithFields();
        component.publicField = newPublicField;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveComponentWithFields() {
        RemoveComponent(TestComponentsLookup.ComponentWithFields);

        return this;
    }


    public TestEntity SafeRemoveComponentWithFields() {
        if (hasComponentWithFields) 
        {
            RemoveComponent(TestComponentsLookup.ComponentWithFields);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherComponentWithFields;

    public static Entitas.IMatcher<TestEntity> ComponentWithFields {
        get {
            if (_matcherComponentWithFields == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.ComponentWithFields);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherComponentWithFields = matcher;
            }

            return _matcherComponentWithFields;
        }
    }
}
