//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public My.Namespace.MyNamespaceComponent myNamespaceMyNamespace { get { return (My.Namespace.MyNamespaceComponent)GetComponent(TestComponentsLookup.MyNamespaceMyNamespace); } }
    public bool hasMyNamespaceMyNamespace { get { return HasComponent(TestComponentsLookup.MyNamespaceMyNamespace); } }

    public TestEntity AddMyNamespaceMyNamespace(string newValue) {
        var index = TestComponentsLookup.MyNamespaceMyNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MyNamespaceComponent)componentPool.Pop()
            : new My.Namespace.MyNamespaceComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceMyNamespaceMyNamespace(string newValue) {
        var index = TestComponentsLookup.MyNamespaceMyNamespace;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (My.Namespace.MyNamespaceComponent)componentPool.Pop()
            : new My.Namespace.MyNamespaceComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveMyNamespaceMyNamespace() {
        RemoveComponent(TestComponentsLookup.MyNamespaceMyNamespace);

        return this;
    }


    public TestEntity SafeRemoveMyNamespaceMyNamespace() {
        if (hasMyNamespaceMyNamespace) 
        {
            RemoveComponent(TestComponentsLookup.MyNamespaceMyNamespace);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiInterfaceGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity : IMyNamespaceMyNamespaceEntity {
    void IMyNamespaceMyNamespaceEntity.AddMyNamespaceMyNamespace(string newValue) { AddMyNamespaceMyNamespace(newValue); }
    void IMyNamespaceMyNamespaceEntity.ReplaceMyNamespaceMyNamespace(string newValue) { ReplaceMyNamespaceMyNamespace(newValue); }
    void IMyNamespaceMyNamespaceEntity.RemoveMyNamespaceMyNamespace() { RemoveMyNamespaceMyNamespace(); }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherMyNamespaceMyNamespace;

    public static Entitas.IMatcher<TestEntity> MyNamespaceMyNamespace {
        get {
            if (_matcherMyNamespaceMyNamespace == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.MyNamespaceMyNamespace);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherMyNamespaceMyNamespace = matcher;
            }

            return _matcherMyNamespaceMyNamespace;
        }
    }
}
