//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public TestMultipleEventsStandardEventRemovedListenerComponent testMultipleEventsStandardEventRemovedListener { get { return (TestMultipleEventsStandardEventRemovedListenerComponent)GetComponent(TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener); } }
    public bool hasTestMultipleEventsStandardEventRemovedListener { get { return HasComponent(TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener); } }

    public TestEntity AddTestMultipleEventsStandardEventRemovedListener(System.Collections.Generic.List<ITestMultipleEventsStandardEventRemovedListener> newValue) {
        var index = TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestMultipleEventsStandardEventRemovedListenerComponent)componentPool.Pop()
            : new TestMultipleEventsStandardEventRemovedListenerComponent();
        component.value = newValue;
        AddComponent(index, component);

        return this;
    }

    public TestEntity ReplaceTestMultipleEventsStandardEventRemovedListener(System.Collections.Generic.List<ITestMultipleEventsStandardEventRemovedListener> newValue) {
        var index = TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener;
        var componentPool = GetComponentPool(index);
        var component = componentPool.Count > 0
            ? (TestMultipleEventsStandardEventRemovedListenerComponent)componentPool.Pop()
            : new TestMultipleEventsStandardEventRemovedListenerComponent();
        component.value = newValue;
        ReplaceComponent(index, component);

        return this;
    }

    public TestEntity RemoveTestMultipleEventsStandardEventRemovedListener() {
        RemoveComponent(TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener);

        return this;
    }


    public TestEntity SafeRemoveTestMultipleEventsStandardEventRemovedListener() {
        if (hasTestMultipleEventsStandardEventRemovedListener) 
        {
            RemoveComponent(TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener);
        }

        return this;
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.ComponentMatcherApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public sealed partial class TestMatcher {

    static Entitas.IMatcher<TestEntity> _matcherTestMultipleEventsStandardEventRemovedListener;

    public static Entitas.IMatcher<TestEntity> TestMultipleEventsStandardEventRemovedListener {
        get {
            if (_matcherTestMultipleEventsStandardEventRemovedListener == null) {
                var matcher = (Entitas.Matcher<TestEntity>)Entitas.Matcher<TestEntity>.AllOf(TestComponentsLookup.TestMultipleEventsStandardEventRemovedListener);
                matcher.componentNames = TestComponentsLookup.componentNames;
                _matcherTestMultipleEventsStandardEventRemovedListener = matcher;
            }

            return _matcherTestMultipleEventsStandardEventRemovedListener;
        }
    }
}

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Entitas.CodeGeneration.Plugins.EventEntityApiGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
public partial class TestEntity {

    public void AddTestMultipleEventsStandardEventRemovedListener(ITestMultipleEventsStandardEventRemovedListener value) {
        var listeners = hasTestMultipleEventsStandardEventRemovedListener
            ? testMultipleEventsStandardEventRemovedListener.value
            : new System.Collections.Generic.List<ITestMultipleEventsStandardEventRemovedListener>();
        listeners.Add(value);
        ReplaceTestMultipleEventsStandardEventRemovedListener(listeners);
    }

    public void RemoveTestMultipleEventsStandardEventRemovedListener(ITestMultipleEventsStandardEventRemovedListener value, bool removeComponentWhenEmpty = true) {
        var listeners = testMultipleEventsStandardEventRemovedListener.value;
        listeners.Remove(value);
        if (removeComponentWhenEmpty && listeners.Count == 0) {
            RemoveTestMultipleEventsStandardEventRemovedListener();
        } else {
            ReplaceTestMultipleEventsStandardEventRemovedListener(listeners);
        }
    }
}
