name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If specific .NET SDK — uncomment and set a version
      # - uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      # Just in case Linux/macOS builder, not sure if I will need it
      # - name: Build on Linux/macOS
      #   if: runner.os != 'Windows'
      #   run: |
      #     chmod +x ./build.sh
      #     ./build.sh

      - name: Build on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: ./build.ps1

      - name: Test
        run: dotnet test --nologo --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ runner.os }}
          path: |
            **/Artifacts/**
          if-no-files-found: warn
          retention-days: 7
