name: Release on tag (Linux)

on:
  push:
    tags:
      - 'v*'   # for example v1.0.0

permissions:
  contents: write

jobs:
  build-test:
    name: Build & Test (Ubuntu)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x' 

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Build (build.sh)
        run: ./build.sh

      - name: Test (solution)
        run: dotnet test ./src/Entitas-Flux/Entitas.sln --nologo --configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-Linux
          path: |
            **/Artifacts/**
          if-no-files-found: error

  release:
    name: Create GitHub Release
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Artifacts-Linux
          path: ./release-bundle

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            Automated release for tag ${{ github.ref_name }}
            Commit: ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            release-bundle/**/*
